"use client";

import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Upload } from "lucide-react";

type ActionItem={id:string;task:string;owner:string;dueDate:string;priority:"High"|"Medium"|"Low"|"Unassigned"};
type Plan={title:string;date:string;decisions:string[];actionItems:ActionItem[];openQuestions:string[];followUps:string[];risks:string[]};
const emptyPlan:Plan={title:"",date:"",decisions:[],actionItems:[],openQuestions:[],followUps:[],risks:[]};

export default function ActionsPage(){
 const[notes,setNotes]=useState("");const[plan,setPlan]=useState<Plan>(emptyPlan);const[stage,setStage]=useState<1|2>(1);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[copied,setCopied]=useState(false);const[fileName,setFileName]=useState("");
 async function generatePlan(){setBusy(true);setError("");try{const res=await fetch("/api/actions/extract",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rawNotes:notes})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not generate the action plan.");setPlan({title:data.meetingTitle||"",date:data.meetingDate||"",decisions:data.decisions||[],openQuestions:data.openQuestions||[],followUps:data.followUps||[],risks:data.risks||[],actionItems:(data.actionItems||[]).map((item:{task:string;owner?:string|null;dueDate?:string|null},index:number)=>({id:`action-${index}-${Date.now()}`,task:item.task,owner:item.owner||"",dueDate:item.dueDate||"",priority:"Unassigned"}))});setStage(2)}catch(e){setError(e instanceof Error?e.message:"Could not generate the action plan.")}finally{setBusy(false)}}
 async function uploadFile(file?:File){if(!file)return; if(file.size>2_000_000){setError("Meeting file is too large. Use a text, markdown, or transcript file under 2 MB.");return;} try{setNotes(await file.text());setFileName(file.name);setError("");setStage(1)}catch{setError("Could not read that file.")}}
 function dateStatus(date:string){if(!date)return"Needs assignment";const p=date.split("-").map(Number);if(p.length!==3||!p[0]||!p[1]||!p[2])return date;const due=new Date(p[0],p[1]-1,p[2]);due.setHours(0,0,0,0);const t=new Date();t.setHours(0,0,0,0);const d=Math.round((due.getTime()-t.getTime())/86400000);if(d<0)return`Overdue by ${Math.abs(d)}d`;if(d===0)return"Due today";if(d<=3)return`Due in ${d}d`;return date}
 function updateAction(id:string,field:keyof ActionItem,value:string){setPlan({...plan,actionItems:plan.actionItems.map(a=>a.id===id?{...a,[field]:value}:a)})}function addAction(){setPlan({...plan,actionItems:[...plan.actionItems,{id:`action-${Date.now()}`,task:"",owner:"",dueDate:"",priority:"Unassigned"}]})}function updateList(key:"decisions"|"openQuestions"|"followUps"|"risks",index:number,value:string){const n=[...plan[key]];n[index]=value;setPlan({...plan,[key]:n})}function addList(key:"decisions"|"openQuestions"|"followUps"|"risks"){setPlan({...plan,[key]:[...plan[key],""]})}function removeList(key:"decisions"|"openQuestions"|"followUps"|"risks",index:number){setPlan({...plan,[key]:plan[key].filter((_,i)=>i!==index)})}
 async function copySummary(){const text=`Meeting: ${plan.title||"Untitled Meeting"}\nDate: ${plan.date||"Unspecified"}\n\nDecisions:\n${plan.decisions.filter(Boolean).map(v=>`• ${v}`).join("\n")}\n\nAction Items:\n${plan.actionItems.filter(a=>a.task.trim()).map(a=>`• [${a.owner||"Unassigned"}] ${a.task} — Due: ${a.dueDate||"None"} — Priority: ${a.priority}`).join("\n")}\n\nFollow-ups:\n${plan.followUps.filter(Boolean).map(v=>`• ${v}`).join("\n")}\n\nRisks / Blockers:\n${plan.risks.filter(Boolean).map(v=>`• ${v}`).join("\n")}\n\nOpen Questions:\n${plan.openQuestions.filter(Boolean).map(v=>`• ${v}`).join("\n")}`;await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),2000)}
 function exportCsv(){const esc=(v:string)=>`"${v.replace(/"/g,'""')}"`;const rows=["Task,Owner,Due Date,Priority,Status",...plan.actionItems.filter(a=>a.task.trim()).map(a=>[a.task,a.owner||"Unassigned",a.dueDate,a.priority,dateStatus(a.dueDate)].map(esc).join(","))];const url=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="ggw-action-plan.csv";a.click();URL.revokeObjectURL(url)}
 function reset(){setNotes("");setPlan(emptyPlan);setStage(1);setError("");setFileName("")}
 const listSection=(key:"decisions"|"openQuestions"|"followUps"|"risks",title:string)=><div className="space-y-2"><div className="flex items-center justify-between"><strong className="text-sm">{title}</strong><Button size="sm" variant="outline" onClick={()=>addList(key)}>+ Add</Button></div>{plan[key].map((value,index)=><div key={`${key}-${index}`} className="flex gap-2"><input className="w-full rounded-md border bg-background p-2 text-sm" value={value} onChange={e=>updateList(key,index,e.target.value)}/><Button size="sm" variant="ghost" onClick={()=>removeList(key,index)}>✕</Button></div>)}</div>;
 return <main className="ops-page mx-auto max-w-6xl px-4 py-10 space-y-6"><section className="ops-hero"><Link className="text-sm underline" href="/workbench">← All workbenches</Link><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold">Meeting → Action Plan</h1><p>Paste or upload meeting notes, then generate an editable action plan.</p></div><Badge variant="outline">Nothing is assigned or sent automatically</Badge></div></section>
 {stage===1&&<Card className="ops-card-orange"><CardHeader><CardTitle>1. Add meeting notes</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><label className="inline-flex cursor-pointer items-center rounded-md border px-4 py-2 text-sm font-medium hover:bg-muted"><Upload className="mr-2 h-4 w-4"/>Upload transcript / notes<input type="file" accept=".txt,.md,.csv,text/plain,text/markdown,text/csv" className="sr-only" onChange={e=>uploadFile(e.target.files?.[0])}/></label>{fileName&&<span className="self-center text-sm font-medium">Loaded: {fileName}</span>}</div><textarea className="min-h-64 w-full rounded-md border bg-background p-3" maxLength={15000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Paste board meeting notes, sponsor debrief notes, event planning notes, or a transcript..."/><div className="flex justify-between text-xs text-muted-foreground"><span>AI extracts only what the notes support.</span><span>{notes.length.toLocaleString()} / 15,000</span></div><Button size="lg" className="w-full md:w-auto" disabled={!notes.trim()||busy} onClick={generatePlan}><Sparkles className="mr-2 h-5 w-5"/>{busy?"Generating Action Plan...":"Generate Action Plan"}</Button>{error&&<p className="text-sm text-red-700">{error}</p>}</CardContent></Card>}
 {stage===2&&<><Card className="ops-card-amber"><CardHeader><CardTitle>2. Review and confirm</CardTitle></CardHeader><CardContent className="space-y-6"><div className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950"><strong>Human control:</strong> confirm owners, deadlines, and priorities before using the plan.</div><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Meeting title<input className="mt-1 w-full rounded-md border bg-background p-2" value={plan.title} onChange={e=>setPlan({...plan,title:e.target.value})}/></label><label className="text-sm">Meeting date<input type="date" className="mt-1 w-full rounded-md border bg-background p-2" value={plan.date} onChange={e=>setPlan({...plan,date:e.target.value})}/></label></div>{listSection("decisions","Decisions")}<div className="space-y-3"><div className="flex items-center justify-between"><strong className="text-sm">Action items</strong><Button size="sm" variant="outline" onClick={addAction}>+ Add action</Button></div>{plan.actionItems.map(a=><div key={a.id} className="grid gap-2 rounded-md border p-3 md:grid-cols-5"><input className="rounded-md border bg-background p-2 md:col-span-2" placeholder="Task" value={a.task} onChange={e=>updateAction(a.id,"task",e.target.value)}/><input className="rounded-md border bg-background p-2" placeholder="Owner" value={a.owner} onChange={e=>updateAction(a.id,"owner",e.target.value)}/><input type="date" className="rounded-md border bg-background p-2" value={a.dueDate} onChange={e=>updateAction(a.id,"dueDate",e.target.value)}/><div className="flex gap-2"><select className="min-w-0 flex-1 rounded-md border bg-background p-2" value={a.priority} onChange={e=>updateAction(a.id,"priority",e.target.value)}><option>Unassigned</option><option>High</option><option>Medium</option><option>Low</option></select><Button variant="ghost" size="sm" onClick={()=>setPlan({...plan,actionItems:plan.actionItems.filter(x=>x.id!==a.id)})}>✕</Button></div><div className="text-xs text-muted-foreground md:col-span-5">Timeline: {dateStatus(a.dueDate)}</div></div>)}</div>{listSection("followUps","Follow-ups")}{listSection("risks","Risks / blockers")}{listSection("openQuestions","Open questions")}</CardContent></Card><Card className="ops-card-green"><CardHeader><CardTitle>3. Use the action plan</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2"><Button onClick={copySummary}>Copy for Google Docs / Gmail</Button><Button variant="outline" onClick={exportCsv}>Download action items CSV</Button><Button variant="ghost" onClick={reset}>Start new meeting</Button>{copied&&<span className="self-center text-sm font-medium">Copied.</span>}</CardContent></Card></>}
 </main>}
