"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { Check, ChevronDown, Copy, ExternalLink, ShieldCheck } from "lucide-react";
import { toolRegistry, type ToolId } from "./tool-registry";

type Category = "all" | "members" | "events" | "communications" | "reporting" | "content" | "automation";
type WorkCategory = Exclude<Category, "all">;

type JobAid = {
  id: string;
  category: WorkCategory;
  title: string;
  summary: string;
  useWhen: string;
  time: string;
  tools: ToolId[];
  steps: string[];
  prompt: string;
  checks: string[];
};

const j = (id: string, category: WorkCategory, title: string, summary: string, useWhen: string, time: string, tools: ToolId[], steps: string[], prompt: string, checks: string[]): JobAid => ({ id, category, title, summary, useWhen, time, tools, steps, prompt, checks });

const jobAids: JobAid[] = [
  // MEMBERS — 6
  j("member-welcome", "members", "Welcome a new member", "Turn approved membership details into a warm first-touch message.", "A new member joins and staff needs a polished welcome quickly.", "3–5 min", ["WildApricot", "Gemini", "Gmail", "Outlook"], ["Open the member record and confirm membership type, join date, approved benefits, and next step.", "Use only the minimum approved fields needed for the draft.", "Review the message, links, recipient, and merge fields before sending."], "Draft a personalized GGW new-member welcome using only these approved facts: [MEMBER FACTS]. Return subject, concise body, CTA, and CHECK BEFORE SENDING. Do not invent benefits, dates, links, eligibility, discounts, events, or commitments.", ["Member status matches WildApricot", "Benefits are approved", "Links work", "Recipient is correct"]),
  j("member-renewal", "members", "Prepare member renewal outreach", "Create renewal messaging from current member status and approved renewal facts.", "A renewal segment is ready for outreach.", "5–10 min", ["WildApricot", "Google Sheets", "Gemini", "Gmail", "Outlook"], ["Define the renewal segment from current WildApricot data.", "Gather approved dates, fees, benefits, terms, and links.", "Draft by segment and verify status before send."], "Create GGW member renewal outreach for [SEGMENT] using only these approved renewal facts: [FACTS]. Return subject, email, CTA, optional reminder, and verification checklist. Do not invent urgency, discounts, benefits, eligibility, fees, deadlines, or payment status.", ["Segment rule is explicit", "Status is current", "Terms match source", "CTA is accurate"]),
  j("member-reengage", "members", "Re-engage lapsed members", "Create respectful outreach without guessing why a member lapsed.", "GGW wants to reconnect with an approved lapsed-member segment.", "5–10 min", ["WildApricot", "Gemini", "Gmail", "Outlook"], ["Confirm the lapsed-member rule and current status.", "Use only approved reasons to reconnect and current opportunities.", "Review tone and remove any unsupported assumptions."], "Draft GGW lapsed-member re-engagement outreach for this approved segment: [SEGMENT]. Approved opportunities/facts: [FACTS]. Approved CTA: [CTA]. Return two message options and a follow-up. Do not infer why anyone lapsed or invent offers, deadlines, eligibility, or benefits.", ["Status is current", "No inferred motivation", "No invented offer", "CTA is approved"]),
  j("member-segmentation", "members", "Segment a member list safely", "Turn an approved member export into useful operational groups without sensitive inference.", "Staff needs actionable member groups for service, outreach, or analysis.", "10 min", ["WildApricot", "Google Sheets", "Gemini"], ["Export only fields needed for the business question.", "Ask for rules based only on fields actually present.", "Validate sample rows from every proposed segment."], "Review this approved GGW member export for [GOAL]. Propose operational segments using only supplied fields. For each show exact rule, fields used, count if calculable, why it matters, and next action. Do not infer protected traits, personal intent, eligibility, or attributes not present in the source.", ["Minimum fields used", "Rules visible", "No sensitive inference", "Sample rows checked"]),
  j("member-data-audit", "members", "Audit member data quality", "Find duplicates, missing fields, inconsistent labels, and stale-looking records before outreach.", "A member list is hard to trust or needs cleanup.", "10–20 min", ["WildApricot", "Google Sheets", "Gemini"], ["Work from an export or controlled working copy.", "Identify quality issues before changing records.", "Send merge/delete decisions back to the record owner for review."], "Audit this approved GGW member export for data quality. Return likely duplicate rules, missing required fields, inconsistent labels, invalid date patterns, stale-looking records based only on explicit dates, and rows requiring human review. Do not merge, delete, or overwrite records.", ["Working copy used", "Duplicate logic visible", "No automatic deletion", "Owner reviews changes"]),
  j("member-faq", "members", "Build a member FAQ from approved sources", "Turn current membership policies and materials into reusable answers staff can trust.", "Staff repeatedly answers the same membership questions.", "10–15 min", ["Google Docs", "Google Drive", "NotebookLM", "Gemini"], ["Collect only current approved membership sources.", "Build questions around joining, benefits, renewals, events, access, and support.", "Cite the source and flag unanswered questions instead of guessing."], "Using only these approved GGW membership sources [SOURCES], create a member FAQ. For every answer name the source section. If the source does not answer the question, write NOT CONFIRMED and identify what needs an owner decision. Do not supplement membership rules from memory.", ["Sources are current", "Answers cite source", "Conflicts are flagged", "No invented policy"]),

  // EVENTS — 6
  j("event-promo", "events", "Turn one event into a promotion kit", "Create coordinated email, social, talking points, and a visual brief from one approved event record.", "An event is approved and ready to promote.", "8–12 min", ["WildApricot", "Gemini", "Canva", "Gmail", "Outlook"], ["Copy the approved event facts from WildApricot.", "Generate channel-specific drafts while locking event facts.", "Compare every asset back to the event record before publishing."], "Create a GGW event promotion kit using only these approved event facts: [FACTS]. Return email, LinkedIn post, short social caption, talking points, Canva brief, reminder copy, and a fact-lock table. Preserve date, time, location, price, eligibility, deadline, and registration URL exactly.", ["Registration URL works", "Date/time match", "Price/eligibility match", "No invented claims"]),
  j("event-registration", "events", "Check event registration health", "Turn registration data into counts, useful groups, missing fields, and follow-up needs.", "Staff needs a quick operational view before an event.", "5–10 min", ["WildApricot", "Google Sheets", "Gemini"], ["Export the minimum registration fields.", "Calculate counts and groups only from explicit fields.", "Validate source rows before using numbers in decisions or outreach."], "Analyze this approved GGW event registration export. Return registration count, cancellations/no-shows if present, useful non-sensitive groups, missing/inconsistent fields, follow-up needs, and operational questions. Identify the source field behind every finding.", ["Counts reconcile", "Cancellations handled", "No sensitive inference", "Sample rows validated"]),
  j("event-run-show", "events", "Build an event run of show", "Convert confirmed logistics into a clear operational timeline.", "An event team needs one execution plan for the day.", "10–20 min", ["Google Docs", "Google Sheets", "Gemini"], ["Gather confirmed timing, speakers, logistics, owners, and dependencies.", "Build the timeline without filling missing owners or times by guess.", "Review the final run of show with the event owner."], "Build a GGW event run of show from these confirmed logistics: [LOGISTICS]. Return time, activity, owner, location/channel, dependency, materials, and contingency note. Use OWNER NEEDED or TIME NEEDED where information is missing. Do not invent logistics.", ["Times are confirmed", "Owners are explicit", "Dependencies visible", "Missing items flagged"]),
  j("event-reminders", "events", "Create event reminder and follow-up messages", "Prepare pre-event and post-event communication from confirmed facts.", "The team needs reminder, attendee, no-show, speaker, or partner messages.", "5–10 min", ["WildApricot", "Gmail", "Outlook", "Gemini"], ["Confirm the intended audience and event status.", "Use approved event facts and links only.", "Verify audience status again before sending."], "Create GGW event communication for [AUDIENCE/STAGE] using only these approved event facts and attendance/registration fields: [FACTS]. Return subject, concise message, CTA, and CHECK BEFORE SENDING. Do not invent attendance, takeaways, resources, future events, or commitments.", ["Audience is correct", "Event facts match", "Links approved", "No invented takeaways"]),
  j("event-feedback", "events", "Turn event feedback into improvements", "Synthesize survey results without overstating what respondents represent.", "Post-event survey responses are ready for review.", "10–15 min", ["Google Forms", "Google Sheets", "Gemini"], ["Use the approved response export.", "Separate measured results from interpretation.", "Turn supported themes into a short improvement list."], "Analyze this approved GGW event feedback export. Return response count, response rate only if denominator is supplied, quantitative results, recurring themes, friction points, and recommended improvements. Distinguish MEASURED RESULTS, INTERPRETATION, and RECOMMENDATIONS. Do not claim results represent all attendees without evidence.", ["Response count correct", "Rate denominator supplied", "Themes source-backed", "PII minimized"]),
  j("event-readiness", "events", "Run a final event readiness check", "Catch missing facts, owners, communications, accessibility, and registration issues before launch.", "An event is approaching launch or delivery.", "10 min", ["WildApricot", "Google Docs", "Gemini"], ["Use the approved event record and operating checklist.", "Mark every item READY, MISSING, or VERIFY.", "Escalate anything that could mislead registrants or block delivery."], "Review these approved GGW event details and return a readiness check for date/time/time zone, location/link, registration URL, price, eligibility, capacity if stated, speakers, accessibility, communications, owner, cancellation language, and follow-up. Do not fill gaps; mark them MISSING or VERIFY.", ["Critical facts verified", "Owners assigned", "Accessibility checked", "Registration path tested"]),

  // COMMUNICATIONS — 6
  j("comm-email", "communications", "Draft a clear GGW email", "Turn approved facts and a desired action into a concise human message.", "You know what needs to be said but want a stronger first draft.", "3–5 min", ["Gmail", "Outlook", "Gemini", "Microsoft Copilot"], ["State audience, purpose, desired action, and approved facts.", "Draft in the approved email/AI tool.", "Check recipients, names, dates, links, attachments, and promises."], "Draft a concise GGW email. Audience: [AUDIENCE]. Purpose: [PURPOSE]. Desired action: [ACTION]. Approved facts: [FACTS]. Required links/attachments: [ITEMS]. Return subject, body, CTA, and CHECK BEFORE SENDING. Do not invent approvals, dates, links, benefits, or commitments.", ["Audience correct", "Facts match source", "Attachments present", "No new promises"]),
  j("comm-thread", "communications", "Summarize a long email thread", "Extract confirmed decisions, asks, actions, and unresolved questions from a long thread.", "An Outlook or Gmail thread is too long to scan manually.", "3–7 min", ["Gmail", "Outlook", "Gemini", "Microsoft Copilot"], ["Use the actual thread or approved source context.", "Separate stated decisions from open questions.", "Verify any action before acting on it."], "Summarize this GGW email thread. Return decisions already made, requests, open questions, action items with owner/date only when stated, unresolved risks, and a suggested reply. Use NOT STATED for missing owners/dates. Do not invent commitments or completion.", ["Decisions trace to thread", "Owners/dates explicit", "No inferred status", "Reply reviewed"]),
  j("comm-partner", "communications", "Draft a sponsor or partner update", "Create a polished external update from confirmed status without creating new commitments.", "A sponsor, partner, speaker, or stakeholder needs an update.", "5–8 min", ["Google Docs", "Gmail", "Outlook", "Gemini", "Microsoft Copilot"], ["List confirmed status, completed items, open questions, and next steps.", "Organize the update without adding promises.", "Verify every deliverable, date, and owner before send."], "Draft a concise GGW sponsor/partner update from these confirmed notes: [NOTES]. Return current status, completed items, next steps with owner/date only when stated, open questions, and closing. Do not invent deliverables, approvals, benefits, dates, or commitments.", ["Status confirmed", "Dates/owners sourced", "No new commitments", "Audience correct"]),
  j("comm-meeting", "communications", "Turn meeting notes into actions", "Convert approved meeting notes into decisions, actions, blockers, and a clean follow-up.", "A meeting ended and the next steps are scattered.", "5–10 min", ["Google Meet", "Google Docs", "Outlook", "Gemini", "Microsoft Copilot"], ["Use the approved recap, transcript, or notes.", "Separate decisions, open questions, and actions.", "Compare the result to source before sharing."], "Turn these GGW meeting notes into a follow-up. Return decisions already made, open questions, actions with owner/date only when stated, blockers, and a short follow-up email. Use NOT STATED for missing owner/date. Do not invent commitments.", ["Decisions match notes", "Owners/dates stated", "Sensitive notes minimized", "No invented commitments"]),
  j("comm-board", "communications", "Prepare a board communication", "Create concise board-facing communication from approved facts, decisions, and materials.", "Leadership needs to notify or prepare the board without overexplaining.", "5–10 min", ["Google Docs", "Gmail", "Outlook", "Gemini", "Microsoft Copilot"], ["Define whether the message is informational, preparatory, or decision-seeking.", "Use approved board dates/materials and documented decisions only.", "Review governance-sensitive wording with the appropriate owner."], "Draft a GGW board communication for [PURPOSE] using only these approved facts and materials: [SOURCES]. Return subject, concise message, requested action/decision only if supplied, attachments/source list, and CHECK BEFORE SENDING. Do not invent board authority, motions, deadlines, approvals, or legal conclusions.", ["Purpose clear", "Board facts sourced", "No invented authority", "Attachments correct"]),
  j("comm-sensitive", "communications", "Respond to a sensitive issue carefully", "Structure a calm internal or external draft without letting AI make legal, HR, or compliance decisions.", "Staff needs help organizing a sensitive response.", "10 min", ["Google Docs", "Gmail", "Outlook", "Gemini"], ["State the audience, confirmed facts, approved position, and required reviewer.", "Draft neutral language that distinguishes facts from unresolved questions.", "Route to the appropriate decision-maker before external use."], "Draft a GGW response regarding [ISSUE] using only these confirmed facts and approved position: [FACTS/POSITION]. Keep the tone factual, calm, and non-accusatory. Identify unresolved questions and required reviewers. Do not make legal, HR, regulatory, disciplinary, or liability conclusions.", ["Facts confirmed", "Reviewer identified", "No legal/HR conclusion", "External use approved"]),

  // REPORTING — 6
  j("report-weekly", "reporting", "Create a weekly operations brief", "Turn approved operating data into a concise snapshot of change, attention, and next action.", "Staff or leadership needs one weekly view.", "10–15 min", ["WildApricot", "Google Sheets", "Google Docs", "Gemini", "Microsoft Copilot"], ["Define reporting period and agreed source metrics.", "Use approved source data and notes.", "Verify every number and separate facts from recommendations."], "Create a GGW weekly operations brief for [DATE RANGE] from these approved metrics and notes: [DATA]. Return headline, member items, event items, operating exceptions, risks/questions, and next actions with owner/date only when supplied. Separate FACTS from RECOMMENDATIONS.", ["Period correct", "Totals tie", "Facts separated", "Sensitive data minimized"]),
  j("report-board", "reporting", "Build a board-ready operating summary", "Translate approved metrics into a concise leadership narrative with sources.", "A board or leadership packet needs an executive summary.", "10–20 min", ["Google Sheets", "Google Docs", "Google Slides", "Gemini", "Microsoft Copilot"], ["Confirm metric definitions and reporting period.", "Separate measured results from interpretation and recommendations.", "Trace every number and claim to the approved source."], "Turn these approved GGW metrics and notes into a board-ready summary. Return executive headline, 3–5 key facts, change versus comparison period if supplied, interpretation clearly labeled, risks/questions, and recommended next steps. Do not infer causation, ROI, or impact without evidence.", ["Metrics source-backed", "Period stated", "No unsupported ROI", "Recommendations labeled"]),
  j("report-membership", "reporting", "Create a membership operating report", "Summarize current membership status, renewal work, data quality, and service actions.", "Leadership needs a membership operations view.", "10–15 min", ["WildApricot", "Google Sheets", "Gemini"], ["Use a current approved membership export.", "Define each metric from actual source fields.", "Flag data-quality limits before interpreting changes."], "Create a GGW membership operating report from this approved export. Return total records, current status mix, renewal counts where explicit, membership-type mix, data-quality issues, operational follow-up groups, and source-field definitions. Do not infer intent, satisfaction, or future renewal.", ["Status definitions explicit", "Counts reconcile", "Data limits stated", "No predictive claims"]),
  j("report-event", "reporting", "Create an event performance report", "Bring registration, attendance, feedback, and approved engagement facts into one evidence-based view.", "An event needs an internal, board, or partner recap.", "10–20 min", ["WildApricot", "Google Forms", "Google Sheets", "Google Docs", "Gemini"], ["Gather approved registration, attendance, and feedback sources.", "Define every metric before comparing results.", "Separate measured results from interpretation and recommendations."], "Create a GGW event performance report from these approved sources: [DATA]. Return registration, attendance if supplied, cancellations/no-shows if supplied, feedback response count, supported themes, operational lessons, and recommendations. Do not invent reach, ROI, causation, sentiment, or outcomes.", ["Sources identified", "Metrics defined", "Feedback limitations stated", "No invented impact"]),
  j("report-grant", "reporting", "Prepare a grant or funder report", "Organize evidence against signed reporting requirements without inventing obligations or outcomes.", "A grant/funder reporting deadline is approaching.", "15–30 min", ["Google Drive", "Google Sheets", "Google Docs", "NotebookLM", "Gemini"], ["Start from the signed agreement and official reporting instructions.", "Map every required section to source evidence.", "Flag missing evidence and route interpretation questions to the right owner."], "Using only the signed GGW grant/funder agreement, official instructions, and approved evidence [SOURCES], build a reporting preparation brief. Return requirement, source clause, evidence available, evidence missing, draft narrative points, reviewer, and official due date. Do not invent requirements, outcomes, allowability, or deadlines.", ["Agreement is authoritative", "Requirements source-cited", "Gaps visible", "Submission reviewed"]),
  j("report-cash", "reporting", "Create a cash-flow working brief", "Summarize approved cash timing data for operational review without making accounting conclusions.", "Leadership needs a short working view of cash timing and uncertainties.", "15–20 min", ["Google Sheets", "Google Docs", "Gemini"], ["Use approved balances, expected receipts, obligations, and timing assumptions.", "Separate confirmed figures from assumptions.", "Route accounting, restriction, and solvency questions to the finance owner."], "Create a GGW cash-flow working brief from these approved figures and assumptions: [DATA]. Return current position as supplied, near-term inflows/outflows, timing uncertainties, scenario notes if supplied, questions for the finance owner, and source references. Do not make accounting, tax, solvency, or restricted-fund conclusions.", ["Figures sourced", "Assumptions labeled", "No finance conclusion", "Owner review required"]),

  // CONTENT — 6
  j("content-board-deck", "content", "Turn approved metrics into a board deck", "Structure a concise presentation without inventing claims, ROI, or conclusions.", "Leadership has approved metrics and needs a board-ready deck.", "15–30 min", ["Google Slides", "Google Sheets", "Google Drive", "Gemini", "Canva"], ["Lock the approved metrics and source links.", "Build slide hierarchy around decisions/questions.", "Fact-check every slide before presenting."], "Create a GGW board deck outline from these approved metrics and notes: [SOURCES]. For each slide provide title, decision/question, approved facts, recommended visual, source reference, and speaker note. Separate FACT, INTERPRETATION, and RECOMMENDATION. Do not invent ROI, benchmarks, quotes, causation, or targets.", ["Metrics locked", "Sources present", "No invented claims", "Slides reviewed"]),
  j("content-event-visual", "content", "Create an event visual brief", "Turn approved event facts into a production brief for Canva or Slides.", "A designer or staff member needs a clear asset brief.", "5–10 min", ["WildApricot", "Canva", "Google Slides", "Gemini"], ["Gather approved event facts and the intended channel/format.", "Define message hierarchy, CTA, and accessibility requirements.", "Protect all event facts from creative drift."], "Create a GGW event visual production brief. Format/channel: [FORMAT]. Approved event facts: [FACTS]. Return headline, hierarchy, CTA, visual direction, image guidance, alt text, and FACT LOCK. Do not invent dates, speakers, pricing, benefits, sponsors, or claims.", ["Fact lock complete", "CTA approved", "Alt text included", "Brand template used"]),
  j("content-member-spotlight", "content", "Create a member spotlight safely", "Create a respectful spotlight from member-approved facts and quotes only.", "GGW has approval to feature a member.", "8–12 min", ["Google Docs", "Canva", "Gemini"], ["Use only facts and quotes the member/owner approved for publication.", "Create short and long versions plus a visual brief.", "Verify name, title, employer, quote, links, and permissions before publishing."], "Create a GGW member spotlight from these publication-approved facts and quotes: [APPROVED CONTENT]. Return headline, short profile, social caption, visual brief, and alt text. Preserve quotes exactly and do not infer identity, career history, achievements, affiliations, or personal details.", ["Publication approval exists", "Quotes exact", "Identity facts verified", "No sensitive additions"]),
  j("content-sponsor-onepager", "content", "Create a sponsor one-pager", "Turn approved sponsorship inventory and organizational facts into a concise first draft.", "GGW needs a sponsor-facing overview or opportunity sheet.", "15–20 min", ["Google Docs", "Canva", "Gemini"], ["Gather approved sponsorship inventory, audience facts, benefits, and contacts.", "Structure the one-pager around value and available opportunities.", "Review every audience, reach, benefit, and price claim before use."], "Create a GGW sponsor one-pager from these approved organizational facts, sponsorship inventory, benefits, prices, and contact details: [FACTS]. Return headline, value proposition, opportunities, approved evidence, CTA, and design brief. Do not invent audience size, ROI, exclusivity, reach, benefits, pricing, or availability.", ["Inventory current", "Claims source-backed", "Pricing approved", "CTA correct"]),
  j("content-sop", "content", "Turn a recurring process into an SOP", "Convert a real GGW workflow into simple, repeatable instructions with owners and checks.", "A task is being done inconsistently or lives in one person's head.", "15–30 min", ["Google Docs", "Google Drive", "Gemini"], ["Document the current process as it actually happens.", "Define trigger, owner, steps, tools, handoffs, exceptions, and verification.", "Test the SOP with someone who did not write it."], "Turn this current GGW process into an SOP: [PROCESS]. Return purpose, trigger, owner, prerequisites, chronological steps, decision points, exception handling, source links, verification, fallback, and review cadence. Do not invent approvals or system capabilities; mark unknowns VERIFY.", ["Current process confirmed", "Owners explicit", "Exceptions covered", "Tested by another user"]),
  j("content-knowledge", "content", "Create a source-grounded knowledge article", "Turn approved policy or process sources into a concise staff reference.", "Staff needs a reusable answer instead of repeatedly asking the same question.", "10–15 min", ["Google Docs", "Google Drive", "NotebookLM", "Gemini"], ["Load only current approved sources.", "Organize the article around the staff question and exact steps.", "Cite source locations and flag conflicts/outdated material."], "Using only these approved GGW sources [SOURCES], create a staff knowledge article for [QUESTION/TASK]. Return quick answer, when it applies, exact steps, source links, exceptions stated in source, verification, and owner/escalation. If sources conflict or are silent, say so instead of guessing.", ["Sources current", "Steps source-grounded", "Conflicts visible", "Owner named"]),

  // AUTOMATION — 6
  j("auto-new-member", "automation", "Automate new-member welcome prep", "Remove repetitive copy/paste while keeping the final welcome behind human review.", "New member records repeatedly trigger the same preparation work.", "20–40 min", ["WildApricot", "Zapier", "Gmail", "Google Sheets"], ["Confirm the available WildApricot trigger and minimum fields.", "Create a draft, not an auto-send, during the pilot.", "Test normal, duplicate, missing-field, and status-reversal cases."], "Design a GGW new-member welcome automation. WildApricot remains the source of truth. Return trigger, minimum fields, actions, stable ID/duplicate protection, draft-first communication step, human approval, error alert, test cases, off switch, and manual fallback. Do not claim a connector action exists unless verified.", ["Trigger verified", "Minimum data", "Draft-first", "Duplicate/reversal tested"]),
  j("auto-registration", "automation", "Automate registration → working Sheet", "Keep an event operations Sheet current without repeated exports and pasted rows.", "Registrations are repeatedly copied into Google Sheets.", "20–45 min", ["WildApricot", "Zapier", "Google Sheets"], ["Verify the current registration trigger in the connector.", "Use a stable registration ID and upsert/update behavior.", "Test create, update, cancellation, duplicate, and permission failure."], "Design a GGW WildApricot registration-to-Google-Sheets automation. Return verified trigger, minimum fields, stable ID, row upsert/update logic, cancellation handling, permission requirements, error alert, tests, off switch, and manual export fallback. Do not assume unsupported connector actions.", ["Stable ID used", "No duplicate rows", "Cancellation tested", "Fallback documented"]),
  j("auto-renewal", "automation", "Automate renewal follow-up preparation", "Prepare renewal worklists or drafts from approved status changes while keeping human review.", "Renewal follow-up requires repeated exports, filters, or draft creation.", "30–60 min", ["WildApricot", "Make", "Google Sheets", "Gmail", "Outlook"], ["Define the exact approved renewal status/trigger.", "Route only the statuses that require action.", "Keep communication draft-first and test reversals/unknown statuses."], "Design a GGW member renewal follow-up automation using WildApricot as the source of truth. Return trigger/status rule, minimum fields, routing, approved-fact source, draft preparation, human review, stable-ID logging, reversal handling, tests, error alert, off switch, and manual fallback.", ["Status rule approved", "Unknown values stop safely", "Draft reviewed", "Reversal tested"]),
  j("auto-event-change", "automation", "Automate event-change preparation", "Prepare updated communication when approved event fields change without auto-publishing.", "Event updates repeatedly require several downstream draft changes.", "30–60 min", ["WildApricot", "Make", "Gmail", "Outlook", "Canva", "Google Sheets"], ["Choose exactly which event-field changes should trigger preparation.", "Preserve previous/current values so the change is visible.", "Prepare drafts only; require owner approval before publishing."], "Design a GGW event-change workflow. Return trigger fields, previous/current value capture, downstream draft-preparation steps, human approval, no-auto-publish rule, duplicate protection, tests for date/time/location/price/link/cancellation changes, error alert, off switch, and fallback.", ["Changes visible", "No auto-publish", "Critical fields tested", "Owner approves release"]),
  j("auto-reporting", "automation", "Automate recurring reporting preparation", "Reduce repeated data collection while keeping source validation and leadership review intact.", "A weekly/monthly report repeats the same extraction and preparation steps.", "45–90 min", ["WildApricot", "Google Sheets", "Google Drive", "Make", "Gemini"], ["Map the current report sources and metric definitions first.", "Automate collection/preparation only where source fields are stable.", "Keep calculation validation and final narrative behind human review."], "Design the simplest safe GGW recurring-report preparation workflow for [REPORT]. Return authoritative sources, trigger/cadence, minimum fields, transformation steps, metric validation, AI preparation step if useful, human review, error handling, duplicate protection, tests, off switch, and manual fallback. Do not invent source-system capabilities.", ["Metric definitions locked", "Source fields stable", "Calculations validated", "Final review retained"]),
  j("auto-decision", "automation", "Decide whether a process should be automated", "Compare manual, Zapier, Make, and custom integration before adding unnecessary complexity.", "A repetitive process feels painful but the right automation level is unclear.", "15–30 min", ["WildApricot", "Zapier", "Make", "Gemini"], ["Write the current manual workflow exactly as it happens.", "Identify source of truth, risk, frequency, exceptions, and approval points.", "Choose the least complex option that safely removes real friction."], "Evaluate this GGW workflow for automation: [WORKFLOW]. Compare keep-manual, Zapier, Make, and API/webhook only if needed. Return trigger, frequency, volume, source of truth, minimum data, exception rate, human approval point, risk, likely benefit, setup complexity, maintenance owner, test plan, fallback, and recommendation. Do not claim connector functionality unless verified.", ["Problem is real", "Source of truth clear", "Human gate retained", "Maintenance owner identified"]),
];

const labels: Record<Category, string> = {
  all: "All help",
  members: "Members",
  events: "Events",
  communications: "Communications",
  reporting: "Reporting",
  content: "Content",
  automation: "Automations",
};

function Card({ item }: { item: JobAid }) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(item.prompt);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1500);
    } catch {
      setCopied(false);
    }
  };
  return <article className={open ? "ggw-aid-card open" : "ggw-aid-card"}>
    <button className="ggw-aid-summary" onClick={() => setOpen(!open)} aria-expanded={open}>
      <span className="ggw-aid-copy"><strong>{item.title}</strong><small>{item.summary}</small><em>{item.category}</em></span>
      <span className="ggw-aid-time">{item.time}</span>
      <ChevronDown className="ggw-aid-chevron" size={19} />
    </button>
    <div className="ggw-aid-tool-links" aria-label="Open tools">
      {item.tools.map((tool) => {
        const link = toolRegistry[tool];
        return <a key={tool} href={link.url} target="_blank" rel="noreferrer"><ExternalLink size={11} />{link.label}</a>;
      })}
    </div>
    {open && <div className="ggw-aid-detail">
      <div className="ggw-aid-use"><strong>Use this when</strong><span>{item.useWhen}</span></div>
      <div className="ggw-three-step"><strong>Do this</strong><ol>{item.steps.map((step) => <li key={step}>{step}</li>)}</ol></div>
      <div className="ggw-prompt-box"><div><strong>Copy this prompt</strong><span>Replace bracketed fields with approved GGW information.</span></div><button onClick={copy}>{copied ? <Check size={15} /> : <Copy size={15} />}{copied ? "Copied" : "Copy prompt"}</button><p>{item.prompt}</p><a className="ggw-open-prompt-library" href={`/prompts?q=${encodeURIComponent(item.title)}`}>Find more GGW prompts</a></div>
      <div className="ggw-check-row"><ShieldCheck size={17} /><div><strong>Before you use the result</strong><span>{item.checks.join(" · ")}</span></div></div>
    </div>}
  </article>;
}

export default function ExpandedJobAids() {
  const [target, setTarget] = useState<HTMLElement | null>(null);
  const [category, setCategory] = useState<Category>("all");

  useEffect(() => {
    const section = document.querySelector<HTMLElement>(".ggw-aids-section");
    if (!section) return;
    section.classList.add("ggw-expanded-ready");
    setTarget(section);
    return () => {
      section.classList.remove("ggw-expanded-ready");
      setTarget(null);
    };
  }, []);

  const filters = useMemo(() => (["all", "members", "events", "communications", "reporting", "content", "automation"] as Category[]).map((id) => ({ id, label: labels[id], count: id === "all" ? jobAids.length : jobAids.filter((item) => item.category === id).length })).filter((item) => item.count > 0), []);
  const visible = useMemo(() => category === "all" ? jobAids : jobAids.filter((item) => item.category === category), [category]);

  if (!target) return null;
  return createPortal(
    <div className="ggw-expanded-job-aids">
      <div className="ggw-section-head"><div><span>Fast help for real GGW work</span><h2>Choose a work area and get the job done.</h2></div><small>{visible.length} job aid{visible.length === 1 ? "" : "s"}</small></div>
      <div className="ggw-filter-row" aria-label="Filter GGW job aids">{filters.map((item) => <button key={item.id} className={category === item.id ? "active" : ""} onClick={() => setCategory(item.id)}>{item.label} <span>({item.count})</span></button>)}</div>
      <div className="ggw-aid-list">{visible.map((item) => <Card key={item.id} item={item} />)}</div>
    </div>,
    target,
  );
}
