import type { PromptItem } from "./prompt-data";

const fp = (
  id: string,
  title: string,
  outcome: PromptItem["outcome"],
  tools: PromptItem["tools"],
  summary: string,
  prompt: string,
  tags: string[],
): PromptItem => ({ id, title, outcome, tools, summary, prompt, tags, level: "Power prompt" });

export const featuredJobDepthPrompts: PromptItem[] = [
  // Member renewal depth — 10 additional prompts; existing library already contains 5 matching prompts.
  fp("member-renewal-depth-01", "Prioritize a member renewal list", "Members", ["WildApricot", "Google Sheets", "Gemini"], "Prioritize renewal work from explicit status and date fields without predicting personal intent.", `Review this approved GGW member renewal export. Using only explicit fields, group records into operational priority bands based on confirmed renewal date/status and any approved service rule I provide: [RULES]. Return the exact rule for each band, count, next action, owner placeholder, and verification check. Do not predict who will renew, infer motivation, or create urgency that is not supported by policy.`, ["member", "renewal", "membership", "prioritization", "operations"]),
  fp("member-renewal-depth-02", "Build a 30-day member renewal workback", "Members", ["WildApricot", "Google Calendar", "Google Sheets", "Gemini"], "Turn confirmed renewal dates into a practical internal workback plan.", `Build a 30-day GGW member renewal workback from these confirmed renewal dates and approved communication rules: [DATA/RULES]. Return recommended internal checkpoints for data review, first outreach, reminder, escalation to an owner, and final status review. Label all suggested timing RECOMMENDED unless it is an approved policy requirement. Do not invent grace periods, benefits, discounts, fees, or deadlines.`, ["member", "renewal", "calendar", "workback"]),
  fp("member-renewal-depth-03", "Create renewal messages by membership type", "Members", ["WildApricot", "Gmail", "Outlook", "Gemini"], "Create distinct renewal drafts while keeping approved benefits and terms locked.", `Create GGW member renewal email drafts by these approved membership types: [TYPES]. Approved renewal facts, benefits, prices, dates, and links: [FACTS]. For each type return subject, preview, concise body, CTA, optional reminder, and CHECK BEFORE SENDING. Preserve approved terms exactly. Do not invent discounts, eligibility, benefits, urgency, exceptions, or payment status.`, ["member", "renewal", "email", "membership"]),
  fp("member-renewal-depth-04", "Audit renewal outreach before send", "Members", ["WildApricot", "Google Sheets", "Gemini"], "Check a renewal campaign for list, fact, and merge-field errors before staff sends it.", `Audit this proposed GGW member renewal campaign against the approved member export and renewal facts I provide. Check segment logic, recipient status, membership type, renewal date, approved benefits, price/fee language, links, merge fields, and exclusions. Return PASS / VERIFY / FIX with the source field behind each finding. Do not assume a member is eligible or due unless the source confirms it.`, ["member", "renewal", "quality", "audit"]),
  fp("member-renewal-depth-05", "Reconcile renewal status after outreach", "Members", ["WildApricot", "Google Sheets", "Gemini"], "Compare outreach tracking with current membership status so follow-up lists stay accurate.", `Reconcile this GGW member renewal outreach tracker with this current approved WildApricot export. Match only on the stable identifiers supplied. Return matched records, status changes, records that should leave the follow-up list, unresolved mismatches, duplicates, and records requiring human review. Do not overwrite either source or infer payment/renewal status from email activity.`, ["member", "renewal", "reconciliation", "status"]),
  fp("member-renewal-depth-06", "Create a lapsed-member renewal recovery plan", "Members", ["WildApricot", "Google Sheets", "Gemini", "Gmail"], "Create respectful recovery outreach without guessing why membership lapsed.", `Build a GGW member renewal recovery plan for this approved lapsed-member segment: [SEGMENT]. Use only confirmed membership history, approved benefits, approved CTA, and approved dates. Return 3 outreach touches, purpose of each, message draft, stop rule, and review checklist. Do not infer why someone lapsed, invent offers, or imply eligibility beyond the source.`, ["member", "renewal", "lapsed", "reengagement"]),
  fp("member-renewal-depth-07", "Prepare renewal talking points for staff", "Members", ["WildApricot", "Google Docs", "Gemini"], "Give staff consistent source-backed answers for common renewal questions.", `Using only these approved GGW membership and renewal materials [SOURCES], create staff talking points for member renewal questions. Cover renewal timing, approved benefits, payment/next-step process, account support, and escalation. Cite the source section for each answer. If the materials do not answer a question, write NOT CONFIRMED and identify the owner who should clarify it.`, ["member", "renewal", "faq", "staff"]),
  fp("member-renewal-depth-08", "Build a renewal dashboard specification", "Reporting", ["WildApricot", "Google Sheets", "Gemini"], "Define a trustworthy renewal dashboard before building charts.", `Design a GGW member renewal dashboard specification from the fields actually available in this WildApricot export: [HEADERS/SAMPLE]. Return metric name, exact definition, numerator/denominator, source field, filter, reporting period, chart type, and validation check. Include counts due, renewed, lapsed, and unresolved only if those statuses exist. Do not invent conversion definitions or classify status from assumptions.`, ["member", "renewal", "dashboard", "reporting"]),
  fp("member-renewal-depth-09", "Find renewal process friction", "Members", ["WildApricot", "Google Sheets", "Gemini"], "Use explicit process and data evidence to identify where renewal work is breaking down.", `Review this GGW member renewal process description plus approved operational data: [PROCESS/DATA]. Identify friction only where the evidence supports it: unclear ownership, missing data, repeated handoffs, late outreach, duplicate work, status ambiguity, or manual re-entry. Return evidence, impact on the process, likely root cause labeled HYPOTHESIS where needed, and smallest improvement to test.`, ["member", "renewal", "process", "improvement"]),
  fp("member-renewal-depth-10", "Create an executive renewal brief", "Reporting", ["WildApricot", "Google Sheets", "Google Docs", "Gemini"], "Summarize the renewal cycle for leadership without unsupported forecasts.", `Create a GGW member renewal executive brief from these approved metrics and notes: [DATA]. Return current period, counts/status mix, changes versus a supplied comparison period, operational blockers, actions underway, decisions needed, and source references. Separate FACTS, INTERPRETATION, and RECOMMENDATIONS. Do not forecast renewal performance or invent causation without evidence.`, ["member", "renewal", "leadership", "reporting"]),

  // Event promotion depth — 13 additional prompts; existing library already contains 2 matching prompts.
  fp("event-promotion-depth-01", "Create an event launch announcement", "Events", ["WildApricot", "Gmail", "Outlook", "Gemini"], "Launch an approved GGW event with consistent facts across email platforms.", `Create a GGW event promotion launch announcement from these approved WildApricot event facts: [FACTS]. Return Gmail/Outlook subject, preview, concise email, CTA, and fact-lock table. Preserve event name, date, time, time zone, location, pricing, eligibility, deadline, and registration URL exactly. Mark missing information [CHECK]; do not invent speakers, capacity, benefits, or urgency.`, ["event", "promotion", "launch", "email"]),
  fp("event-promotion-depth-02", "Build an event social promotion sequence", "Events", ["WildApricot", "Gemini", "Canva"], "Create a coordinated multi-post sequence without changing approved event facts.", `Build a GGW event promotion social sequence from these approved facts: [FACTS]. Return 6 posts covering launch, value, speaker/topic spotlight only if confirmed, reminder, final approved deadline reminder, and day-of message. Include headline, caption, CTA, visual brief, alt text, and FACT LOCK for each. Do not invent speakers, quotes, benefits, deadlines, or scarcity.`, ["event", "promotion", "social", "canva"]),
  fp("event-promotion-depth-03", "Create an event reminder campaign", "Events", ["WildApricot", "Gmail", "Outlook", "Gemini"], "Build reminder messages around confirmed milestones and registration facts.", `Create a GGW event promotion reminder campaign using only these approved event facts and confirmed milestones: [FACTS/MILESTONES]. Return recommended reminder timing, audience, subject, message, CTA, and check. Clearly label suggested timing RECOMMENDED unless it is an approved deadline. Do not invent urgency, capacity, pricing changes, benefits, or eligibility.`, ["event", "promotion", "reminder", "email"]),
  fp("event-promotion-depth-04", "Create a speaker spotlight", "Events", ["WildApricot", "Google Docs", "Gemini", "Canva"], "Promote a confirmed speaker using only approved bio and session information.", `Create a GGW event promotion speaker spotlight from this approved speaker bio, session title, event record, and approved quote if any: [SOURCES]. Return social caption, email module, Canva brief, alt text, and fact check. Do not invent credentials, employer, title, quote, session promise, or event details.`, ["event", "promotion", "speaker", "content"]),
  fp("event-promotion-depth-05", "Create a partner promotion toolkit", "Events", ["WildApricot", "Google Docs", "Canva", "Gemini"], "Give approved partners ready-to-share event promotion copy and assets.", `Create a GGW event promotion toolkit for approved partners using these confirmed event facts and partner guidelines: [SOURCES]. Return 2 social captions, short newsletter blurb, email-forward copy, approved CTA, visual requirements, and fact-lock table. Do not imply sponsorship benefits, exclusivity, audience size, or partner commitments not in the source.`, ["event", "promotion", "partner", "toolkit"]),
  fp("event-promotion-depth-06", "Create an event landing-page copy review", "Events", ["WildApricot", "Gemini"], "Improve clarity of an existing event page without changing facts.", `Review this GGW WildApricot event page copy against the approved event record: [PAGE + SOURCE FACTS]. Return clarity improvements, missing decision-useful information, duplicated text, CTA issues, accessibility/readability concerns, and a revised version. Preserve all factual fields exactly and flag conflicts rather than resolving them by guess.`, ["event", "promotion", "wildapricot", "landing page"]),
  fp("event-promotion-depth-07", "Create segmented event promotion", "Events", ["WildApricot", "Google Sheets", "Gmail", "Gemini"], "Tailor event promotion by explicit member segment without sensitive inference.", `Create GGW event promotion drafts for these approved member segments: [SEGMENTS]. Use only explicit segment fields and approved event facts. For each segment return why the event is relevant based only on supplied facts, subject, concise email, CTA, and check. Do not infer interests, career goals, demographics, or eligibility not explicitly present.`, ["event", "promotion", "members", "segmentation"]),
  fp("event-promotion-depth-08", "Build an event promotion calendar", "Events", ["WildApricot", "Google Calendar", "Gemini"], "Plan promotion around the confirmed event date and registration deadline.", `Build a GGW event promotion calendar from these confirmed event dates, deadlines, audiences, and channels: [FACTS]. Return recommended publish date, purpose, audience, channel, source asset needed, owner placeholder, and verification step. Label proposed dates RECOMMENDED. Do not invent registration deadlines, event milestones, or communication requirements.`, ["event", "promotion", "calendar", "planning"]),
  fp("event-promotion-depth-09", "Repurpose one event message across channels", "Events", ["WildApricot", "Gemini", "Canva"], "Adapt one approved message to multiple channels while keeping the same facts.", `Repurpose this approved GGW event promotion message across [CHANNELS]. Return channel-specific copy, CTA, length adjustment, visual note, and accessibility note. Maintain a shared FACT LOCK containing date, time, location, registration URL, pricing, eligibility, and deadline. Do not introduce new claims or details during adaptation.`, ["event", "promotion", "repurpose", "content"]),
  fp("event-promotion-depth-10", "Create an event FAQ for promotion", "Events", ["WildApricot", "Google Docs", "Gemini"], "Answer prospective attendee questions from approved event materials only.", `Using only the approved GGW event record and policy/logistics sources [SOURCES], create a promotional FAQ covering who the event is for, date/time/time zone, location/access, pricing, registration, eligibility, accessibility, cancellation/contact details only when confirmed. Cite the source field/section. Write NOT CONFIRMED where the source is silent.`, ["event", "promotion", "faq", "registration"]),
  fp("event-promotion-depth-11", "Audit an event promotion campaign", "Events", ["WildApricot", "Google Docs", "Gemini"], "Check campaign assets against the event source before publishing.", `Audit these GGW event promotion assets against the approved WildApricot event record: [ASSETS + SOURCE]. Check title, date, time, time zone, location, registration URL, deadline, price, eligibility, speaker names/titles, sponsor references, CTA, and accessibility. Return PASS / FIX / VERIFY for every asset and identify the exact conflict.`, ["event", "promotion", "quality", "audit"]),
  fp("event-promotion-depth-12", "Create a low-registration promotion response", "Events", ["WildApricot", "Google Sheets", "Gemini"], "Respond to a confirmed registration gap without inventing causes or fake urgency.", `Using this approved GGW event registration snapshot and promotion history [DATA], prepare a low-registration event promotion response. Return confirmed facts, possible explanations labeled HYPOTHESES, 5 low-risk promotional actions, audiences/channels supported by existing data, message drafts using only approved event facts, and metrics to monitor. Do not invent scarcity, blame channels, or claim causes not proven.`, ["event", "promotion", "registration", "optimization"]),
  fp("event-promotion-depth-13", "Create a final event promotion readiness brief", "Events", ["WildApricot", "Google Docs", "Gemini"], "Give the owner one final pre-launch view of facts, assets, audiences, and approvals.", `Create a final GGW event promotion readiness brief using these approved event facts, planned assets, audiences, channels, and owners: [SOURCES]. Return READY / MISSING / VERIFY for event facts, registration path, email, social, visuals, partner assets, accessibility, approvals, tracking, and owner. Do not fill missing facts. Prioritize anything that could mislead a prospective attendee.`, ["event", "promotion", "readiness", "operations"]),

  // Grant depth — 2 additional prompts; existing library already contains 13 matching prompts.
  fp("grant-depth-01", "Build a grant closeout checklist", "Finance & Admin", ["Google Drive", "Google Sheets", "Google Docs", "Gemini"], "Turn signed award and closeout requirements into a source-backed checklist.", `Using only this signed GGW grant agreement and funder closeout instructions [SOURCES], build a grant closeout checklist. Return requirement, exact source clause/location, evidence needed, responsible owner placeholder, official due date, recommended internal review date, submission method, retention location, and verification step. Do not invent allowability, deadlines, extensions, or funder requirements.`, ["grant", "closeout", "funder", "compliance"]),
  fp("grant-depth-02", "Prepare grant renewal or continuation questions", "Research", ["Google Drive", "NotebookLM", "Gemini"], "Use current award materials to identify what must be confirmed before pursuing continuation funding.", `Review these approved GGW grant/funder sources [SOURCES] and prepare a continuation/renewal question set. Return confirmed current award facts, any continuation language explicitly stated, performance/reporting evidence available, information gaps, questions for the funder, and internal readiness questions. Do not assume renewal eligibility, future funding, deadlines, or unchanged terms.`, ["grant", "renewal", "funder", "research"]),

  // Cash-flow depth — 12 additional prompts; existing library already contains 3 matching prompts.
  fp("cash-flow-depth-01", "Build a 13-week cash-flow working forecast", "Finance & Admin", ["Google Sheets", "Gemini"], "Structure a short-term cash-flow view from approved balances and expected inflows/outflows.", `Build a 13-week GGW cash flow working forecast from these approved opening balances, expected receipts, committed payments, payroll/recurring obligations, and timing assumptions: [DATA]. Return weekly beginning cash, inflows by source, outflows by category, ending cash, and assumptions. Separate CONFIRMED from ASSUMED timing. Flag missing data and do not make accounting, solvency, or fund-availability conclusions.`, ["cash", "flow", "finance", "forecast"]),
  fp("cash-flow-depth-02", "Create cash-flow scenarios", "Finance & Admin", ["Google Sheets", "Gemini"], "Compare timing scenarios without presenting them as predictions.", `Create GGW cash flow scenarios using this approved baseline: [DATA]. Model BASE, RECEIPTS-DELAYED, and COST-TIMING scenarios using only the changes I specify: [SCENARIO RULES]. Return weekly ending cash, lowest point, timing driver, and assumptions. Label every scenario illustrative, not a forecast guarantee. Do not change restricted-fund treatment or infer available cash without finance-owner confirmation.`, ["cash", "flow", "scenario", "finance"]),
  fp("cash-flow-depth-03", "Audit cash-flow inputs", "Finance & Admin", ["Google Sheets", "Gemini"], "Check the source inputs before relying on a cash-flow model.", `Audit these GGW cash flow inputs before modeling: [DATA]. Check date completeness, duplicate items, sign direction, recurring obligations, one-time items, opening balance source, restricted/unrestricted labeling only where supplied, expected receipt evidence, and missing timing assumptions. Return PASS / VERIFY / FIX and do not alter the source.`, ["cash", "flow", "audit", "finance"]),
  fp("cash-flow-depth-04", "Explain a cash-flow variance", "Reporting", ["Google Sheets", "Gemini"], "Explain why actual cash movement differed from the approved plan using supplied transactions only.", `Compare this approved GGW cash flow plan with actual cash movements for [PERIOD]. Return variance by major category, timing shifts, one-time items, missing/unmatched items, and questions for the finance owner. Separate VERIFIED VARIANCE from POSSIBLE EXPLANATION. Do not infer accounting treatment, unrestricted availability, or financial health.`, ["cash", "flow", "variance", "reporting"]),
  fp("cash-flow-depth-05", "Build a monthly cash-flow bridge", "Reporting", ["Google Sheets", "Google Docs", "Gemini"], "Explain beginning-to-ending cash with a source-backed bridge.", `Build a GGW cash flow bridge for [MONTH] using these approved balances and cash movements: [DATA]. Return beginning cash, major inflow categories, major outflow categories, timing/reclassification items only if explicitly provided, ending cash, and reconciliation difference. Identify the source for each number and flag anything that does not reconcile.`, ["cash", "flow", "bridge", "finance"]),
  fp("cash-flow-depth-06", "Create a cash-flow assumptions register", "Finance & Admin", ["Google Sheets", "Google Docs", "Gemini"], "Make every timing assumption visible and reviewable.", `Create a GGW cash flow assumptions register from this working forecast: [FORECAST/NOTES]. Return assumption, category, amount if supplied, expected date/range, source/evidence, owner, confidence as USER-SUPPLIED / SOURCE-CONFIRMED / UNCONFIRMED, next review date, and impact if wrong. Do not assign confidence based on model intuition.`, ["cash", "flow", "assumptions", "controls"]),
  fp("cash-flow-depth-07", "Prepare a cash-flow leadership brief", "Reporting", ["Google Sheets", "Google Docs", "Gemini"], "Summarize cash timing for leadership without making unsupported finance conclusions.", `Create a GGW cash flow leadership brief from these approved figures and assumptions: [DATA]. Return current cash position as supplied, expected near-term inflows/outflows, material timing uncertainties, scenario range if supplied, decisions/questions for leadership, and source references. Do not characterize liquidity as healthy/unhealthy or make solvency, accounting, tax, or fund-availability conclusions.`, ["cash", "flow", "leadership", "reporting"]),
  fp("cash-flow-depth-08", "Identify cash timing conflicts", "Finance & Admin", ["Google Sheets", "Google Calendar", "Gemini"], "Surface weeks where confirmed obligations and expected receipts create timing pressure.", `Review this GGW cash flow schedule and identify timing conflicts using only confirmed/approved dates and amounts: [DATA]. Return week, confirmed outflows, expected inflows, net movement, assumptions, and items needing finance-owner review. Do not recommend delaying obligations or moving restricted funds. Provide questions rather than financial directives.`, ["cash", "flow", "timing", "calendar"]),
  fp("cash-flow-depth-09", "Reconcile cash-flow forecast to bank working data", "Finance & Admin", ["Google Sheets", "Gemini"], "Find unmatched forecast and actual cash items without altering records.", `Reconcile this GGW cash flow forecast to this approved bank/transaction working export for [PERIOD]. Match by date, amount, and supplied reference fields. Return matched items, timing differences, unmatched forecast items, unmatched actual items, duplicates, and items requiring finance-owner review. Do not infer accounting category or delete/merge records.`, ["cash", "flow", "reconciliation", "finance"]),
  fp("cash-flow-depth-10", "Build a recurring cash commitments schedule", "Finance & Admin", ["Google Sheets", "Google Calendar", "Gemini"], "Turn approved recurring commitments into a visible schedule.", `Using this approved GGW recurring commitment list [DATA], create a cash flow commitments schedule. Return vendor/obligation, approved amount or range, frequency, confirmed next due date, owner, source agreement/file, cancellation/renewal date only if supplied, and review note. Do not invent contract terms or assume an item can be canceled.`, ["cash", "flow", "recurring", "commitments"]),
  fp("cash-flow-depth-11", "Prepare cash-flow questions for the treasurer or finance owner", "Finance & Admin", ["Google Sheets", "Google Docs", "Gemini"], "Turn unclear model inputs into a focused review agenda.", `Review this GGW cash flow working model and create questions for the treasurer/finance owner. Focus on missing source support, timing assumptions, restricted/unrestricted labels, unusual amounts, duplicate items, stale estimates, and unreconciled differences. Rank questions by decision impact. Do not answer accounting, tax, or fund-restriction questions yourself.`, ["cash", "flow", "treasurer", "review"]),
  fp("cash-flow-depth-12", "Create a cash-flow model validation checklist", "Finance & Admin", ["Google Sheets", "Gemini"], "Verify structure, formulas, sources, and assumptions before leadership uses the model.", `Create a validation checklist for this GGW cash flow model: [MODEL DESCRIPTION / FORMULAS / SAMPLE]. Check opening balance, formula ranges, signs, dates, duplicates, inflow/outflow classification as supplied, scenario formulas, ending-cash roll-forward, source links, assumptions, and reconciliation. Return test, expected result, actual result placeholder, and owner. Do not certify the model as an audit or accounting opinion.`, ["cash", "flow", "validation", "finance"]),

  // Microsoft Copilot depth — 8 additional prompts; existing library already contains 7 matching prompts.
  fp("copilot-depth-01", "Draft a GGW executive email with Copilot", "Communications", ["Outlook", "Microsoft Copilot"], "Create an executive-ready Outlook draft from approved facts and a clear ask.", `Using only the approved GGW facts I provide or that this authorized Microsoft 365 Copilot session can access, draft an executive email for [AUDIENCE] about [PURPOSE]. Return subject, concise body, decision/request, deadline only if confirmed, and CHECK BEFORE SENDING. Preserve source facts and do not invent approvals, commitments, dates, or attachments. If source access is unavailable, say what must be pasted manually.`, ["copilot", "outlook", "email", "executive"]),
  fp("copilot-depth-02", "Prepare a board meeting with Copilot", "Meetings", ["Outlook", "Microsoft Copilot"], "Use authorized Microsoft 365 context to prepare a source-backed board meeting brief.", `Prepare me for this GGW board meeting using only the approved files, emails, calendar items, and notes I provide or that my authorized Microsoft 365 Copilot experience can access. Return meeting objective, confirmed decisions pending, source-backed facts, unresolved questions, proposed agenda, materials to review, and verification checklist. Do not invent board positions, approvals, fiduciary conclusions, or deadlines.`, ["copilot", "board", "meeting", "preparation"]),
  fp("copilot-depth-03", "Summarize a Copilot meeting recap safely", "Meetings", ["Microsoft Copilot", "Outlook"], "Turn an available meeting recap into decisions and actions while preserving source uncertainty.", `Using this GGW meeting recap/transcript or authorized Copilot meeting context [SOURCE], return decisions already stated, action items with owner/date only when explicit, open questions, risks/blockers, and a follow-up draft. Cite or identify the source when available. Use NOT STATED for missing owner/date and do not infer commitments.`, ["copilot", "meeting", "recap", "actions"]),
  fp("copilot-depth-04", "Create a Copilot document review brief", "Research", ["Microsoft Copilot"], "Review approved Microsoft 365 documents for decisions, gaps, and questions without claiming inaccessible context.", `Review these approved GGW Microsoft 365 documents or the authorized Copilot context available in this session for [PURPOSE]. Return verified facts, decisions already documented, contradictions, missing information, deadlines explicitly stated, and questions for the owner. Identify the source for each material fact. If a source is not accessible, state ACCESS NOT AVAILABLE.`, ["copilot", "document", "review", "research"]),
  fp("copilot-depth-05", "Build a Copilot weekly priority brief", "Reporting", ["Outlook", "Microsoft Copilot"], "Create a weekly view from confirmed Microsoft 365 commitments and upcoming dates.", `Create a GGW weekly priority brief for [DATE RANGE] from the emails, calendar items, files, and notes I provide or that my authorized Copilot session can access. Return confirmed commitments, upcoming confirmed deadlines, decisions needed, open questions, and recommended follow-ups. Separate SOURCE FACTS from RECOMMENDATIONS; do not infer ownership, status, or completion.`, ["copilot", "weekly", "priorities", "reporting"]),
  fp("copilot-depth-06", "Create a Copilot stakeholder update", "Communications", ["Outlook", "Microsoft Copilot"], "Prepare a source-grounded stakeholder update without creating new promises.", `Using only approved GGW Microsoft 365 context available to this Copilot session or supplied here [SOURCES], draft a stakeholder update for [AUDIENCE]. Return confirmed progress, decisions already made, next steps with owner/date only when stated, open questions, and concise closing. Cite/identify source context where available. Do not invent status, completion, commitments, or dates.`, ["copilot", "stakeholder", "update", "outlook"]),
  fp("copilot-depth-07", "Compare two source documents with Copilot", "Research", ["Microsoft Copilot"], "Compare approved documents while keeping differences traceable to source.", `Compare these two approved GGW documents using Copilot only if both are available in this session: [DOCUMENT A] and [DOCUMENT B]. Return material differences, additions, removals, changed dates/amounts/terms, conflicts, and questions for the owner. Quote minimally and identify the source/location of each difference. Do not decide which version is authoritative unless the user supplies that governance rule.`, ["copilot", "compare", "documents", "research"]),
  fp("copilot-depth-08", "Create a Copilot action tracker from email and meetings", "Reporting", ["Outlook", "Microsoft Copilot"], "Turn confirmed Microsoft 365 actions into a reviewable tracker.", `Using the authorized GGW Outlook/Copilot context for [DATE RANGE] or the content I provide, create an action tracker with action, source email/meeting, owner only if explicit, due date only if explicit, status only if stated, dependency, and source reference. Separate CONFIRMED ACTIONS from POSSIBLE FOLLOW-UPS. Do not infer ownership, deadlines, completion, or priority.`, ["copilot", "actions", "outlook", "reporting"]),
];
