import type { PromptItem } from "./prompt-data";

const ep = (
  id: string,
  title: string,
  outcome: PromptItem["outcome"],
  tools: PromptItem["tools"],
  summary: string,
  prompt: string,
  tags: string[],
  level: PromptItem["level"] = "Power prompt",
): PromptItem => ({ id, title, outcome, tools, summary, prompt, tags, level });

export const platformExpansionPrompts: PromptItem[] = [
  ep("calendar-reporting-cadence", "Build the GGW reporting cadence in Google Calendar", "Reporting", ["Google Calendar", "Google Sheets", "Google Drive", "Gemini"], "Turn confirmed board, finance, program, membership, event, grant, and compliance reporting dates into a visible operating cadence.", `Build a GGW reporting cadence using only these confirmed reporting obligations and operating dates: [PASTE CONFIRMED DATES / SOURCE REQUIREMENTS]. Return a table with report or review, authoritative source, reporting period, due date, recommended internal draft date, recommended review date, owner placeholder, source-file location, and reminder cadence. Clearly label internal draft/review dates as RECOMMENDED unless already approved. Flag collisions, missing owners, missing source files, and deadlines that need confirmation. Do not invent board, tax, grant, regulatory, or funder deadlines. End with the exact Google Calendar events that should be created after human approval.`, ["reporting", "calendar", "deadlines", "board", "grant", "operations"]),
  ep("calendar-board-reporting-cycle", "Plan the board reporting cycle", "Reporting", ["Google Calendar", "Google Drive", "Google Docs", "Google Sheets", "Gemini"], "Work backward from confirmed board dates so metrics, committee inputs, financials, and packet review happen on time.", `Create a GGW board reporting workback plan from these confirmed board meeting dates and approved packet requirements: [DATES AND REQUIREMENTS]. For each meeting return: source-data cutoff, committee input deadline, finance/reporting input deadline, first-draft date, leadership review date, packet finalization date, distribution date only if policy states one, owner placeholder, and source folder. Clearly label any proposed internal timing as RECOMMENDED. Do not invent bylaws, notice requirements, board deadlines, or approval rules. Flag any step that needs the board secretary, treasurer, executive lead, or qualified advisor to confirm.`, ["board", "reporting", "calendar", "governance", "workback"]),
  ep("calendar-grant-reporting", "Build a grant and funder reporting calendar", "Reporting", ["Google Calendar", "Google Sheets", "Google Drive", "Gemini"], "Translate signed award requirements into a controlled schedule for evidence collection, draft reporting, review, and submission.", `Using only the signed grant/funder agreements and reporting instructions supplied here [SOURCES], create a GGW grant-reporting calendar. For each obligation return funder/grant, exact requirement, reporting period, official due date, source clause/location, evidence needed, recommended evidence-freeze date, recommended draft date, reviewer, submission owner placeholder, and file location. Mark internal planning dates RECOMMENDED. Put anything unclear in VERIFY WITH FUNDER / QUALIFIED ADVISOR. Do not invent reporting obligations, allowability rules, extensions, or deadlines.`, ["grant", "funder", "reporting", "calendar", "compliance"]),
  ep("forms-reporting-summary", "Turn Google Forms responses into a decision-ready report", "Reporting", ["Google Forms", "Google Sheets", "Gemini"], "Convert survey or intake responses into counts, themes, limitations, and next actions without overstating what respondents represent.", `Analyze this approved GGW Google Forms response export for [PURPOSE]. Return response count, response rate only if the denominator is supplied, exact quantitative results, recurring qualitative themes with paraphrased examples, missing-data issues, segment comparisons only when supported by explicit non-sensitive fields, and recommended actions. Separate MEASURED RESULTS, INTERPRETATION, and RECOMMENDATIONS. Do not claim the responses represent all members or attendees unless the evidence supports it. Remove unnecessary personal identifiers from the reporting output.`, ["forms", "survey", "reporting", "feedback", "analysis"]),
  ep("meet-action-report", "Create a cross-meeting action report", "Reporting", ["Google Meet", "Google Docs", "Google Sheets", "Gemini"], "Roll approved meeting recaps into one operational view of decisions, actions, blockers, and overdue items.", `Using these approved GGW meeting recaps or notes [PASTE / SOURCE], create a cross-meeting action report. Return: decision, meeting/date, action item, owner only if stated, due date only if stated, status only if supplied, dependency/blocker, and source reference. Then summarize recurring blockers and decisions requiring leadership attention. Use NOT STATED for missing owners/dates/status. Do not infer completion, assign owners, or create commitments.`, ["meetings", "reporting", "actions", "operations", "follow-up"]),
  ep("drive-reporting-source-pack", "Build a reporting source pack from Google Drive", "Reporting", ["Google Drive", "Google Sheets", "Google Docs", "Gemini"], "Identify the approved files behind a recurring report so staff can reproduce it without hunting through Drive.", `Build a GGW reporting source pack for [REPORT / BOARD PACKET / FUNDER REPORT / OPERATING REVIEW] using only the file inventory and approved Drive locations I provide: [PASTE]. Return required metric or section, authoritative source file, file owner if known, reporting period, extraction method, last-updated date if available, known data-quality concern, and verification step. Flag duplicate or conflicting files and recommend which owner should resolve them. Do not declare a file authoritative unless the supplied evidence says so.`, ["drive", "reporting", "source of truth", "board", "operations"]),
  ep("slides-board-report", "Turn approved metrics into a board reporting deck", "Reporting", ["Google Slides", "Google Sheets", "Google Drive", "Gemini"], "Structure a concise board deck from approved metrics while keeping facts, interpretation, and decisions separate.", `Create a GGW board-reporting deck outline using only these approved metrics, notes, and source links: [PASTE]. Return no more than [SLIDE COUNT] slides. For each slide provide title, decision/question supported, 2–4 approved facts, recommended chart or visual, source reference, and speaker note. Separate FACT, INTERPRETATION, and RECOMMENDATION. Do not invent ROI, causation, targets, benchmarks, quotes, or financial conclusions. End with a slide-level fact-check list before presentation.`, ["slides", "board", "reporting", "metrics", "presentation"]),
  ep("notebooklm-reporting-brief", "Build a source-grounded leadership brief with NotebookLM", "Reporting", ["NotebookLM", "Google Drive", "Google Docs"], "Use an approved source set to create a leadership or committee brief with traceable evidence.", `Using only the approved sources loaded into this NotebookLM notebook, prepare a GGW [LEADERSHIP / BOARD / COMMITTEE / PROGRAM] brief for [PURPOSE]. Return key facts, decisions already documented, unresolved questions, deadlines stated in sources, risks explicitly identified in sources, and recommended discussion questions. Cite the supporting source for every factual statement. If a claim cannot be supported by the loaded sources, label it NOT SUPPORTED BY CURRENT SOURCES. Do not supplement with memory or outside facts unless the user explicitly requests external research.`, ["notebooklm", "reporting", "leadership", "sources", "brief"]),
  ep("outlook-ggw-email", "Draft a GGW email in Outlook", "Communications", ["Outlook", "Microsoft Copilot"], "Create a clear first draft for Outlook users while preserving approved GGW facts and keeping human review before send.", `Draft a concise GGW Outlook email. AUDIENCE: [AUDIENCE]. PURPOSE: [PURPOSE]. DESIRED ACTION: [ACTION]. APPROVED FACTS: [FACTS]. REQUIRED LINKS/ATTACHMENTS: [ITEMS]. Tone: confident, welcoming, inclusive, and human. Return subject line, email body, CTA, and CHECK BEFORE SENDING. Preserve all supplied dates, amounts, eligibility rules, links, and commitments exactly. Do not invent decisions, approvals, benefits, deadlines, or promises. If Copilot in Outlook is unavailable for this account, use the same prompt in an approved AI tool and paste only the minimum necessary source information.`, ["outlook", "email", "copilot", "communications"]),
  ep("outlook-thread-actions", "Summarize an Outlook thread into decisions and actions", "Communications", ["Outlook", "Microsoft Copilot"], "Use Copilot in Outlook where available to catch up on a long thread, then verify the source messages before acting.", `Summarize this GGW Outlook email thread. Return: decisions already made, requests made, open questions, action items with owner/date only when explicitly stated, unresolved risks, and a suggested reply to the latest ask. For each decision/action identify the message or passage that supports it when the product provides citations; otherwise tell me what I should manually verify in the thread. Use NOT STATED for missing owner/date. Do not invent commitments.`, ["outlook", "thread", "summary", "actions", "copilot"]),
  ep("outlook-meeting-prep", "Prepare for a GGW meeting with Outlook + Copilot", "Meetings", ["Outlook", "Microsoft Copilot"], "Use available Outlook/Copilot context to prepare an agenda and open questions, with a manual-source fallback when connected context is unavailable.", `Help me prepare for this GGW meeting: [MEETING / PURPOSE]. Use only the approved email, calendar, document, and meeting context I provide or that my authorized Microsoft 365 Copilot experience can access. Return meeting objective, relevant confirmed context, decisions already made, open questions, proposed agenda, documents to review, and my preparation checklist. Do not infer commitments or decisions. If Copilot cannot access a referenced email/file/meeting, say ACCESS NOT AVAILABLE and tell me what to paste or open manually.`, ["outlook", "meeting", "agenda", "copilot", "preparation"]),
  ep("outlook-weekly-commitments", "Create a weekly commitments report from Outlook", "Reporting", ["Outlook", "Microsoft Copilot"], "Turn confirmed email/calendar commitments into a weekly operating list without treating AI inference as a commitment.", `Create a GGW weekly commitments report from the Outlook email/calendar content I provide or that my authorized Copilot experience can access for [DATE RANGE]. Return commitment/request, source email or meeting, owner only if explicitly stated, due date only if explicitly stated, current status only if stated, dependency, and recommended follow-up. Separate CONFIRMED COMMITMENTS from POSSIBLE FOLLOW-UPS. Do not infer deadlines, owners, or completion. If citations/source links are available, preserve them for verification.`, ["outlook", "reporting", "commitments", "weekly", "copilot"]),
  ep("copilot-weekly-ops", "Build a weekly GGW operations brief with Microsoft Copilot", "Reporting", ["Microsoft Copilot", "Outlook"], "Use approved or authorized Microsoft 365 context to summarize the week while keeping facts traceable to source material.", `Create a GGW weekly operations brief for [DATE RANGE] using only the emails, meetings, files, and notes I provide or that my authorized Microsoft 365 Copilot experience can access. Return: key confirmed developments, decisions already made, upcoming confirmed deadlines, unresolved questions, risks explicitly stated in source material, and recommended follow-up. Cite or identify the source for every factual item when available. Separate SOURCE FACTS from RECOMMENDATIONS. Do not infer project status, completion, owner, deadline, financial impact, or organizational commitment.`, ["copilot", "reporting", "weekly brief", "operations", "outlook"]),
  ep("copilot-source-research", "Run source-grounded research with Microsoft Copilot", "Research", ["Microsoft Copilot"], "Use Copilot as a research assistant while keeping source quality, access boundaries, and unsupported claims visible.", `Research this GGW question: [QUESTION]. Scope: [SCOPE]. Use authoritative sources first and distinguish organizational Microsoft 365 content from public web sources. For every material claim provide the source title/link or identify the internal source if available. Separate VERIFIED FACTS, SOURCE LIMITATIONS, INTERPRETATION, and RECOMMENDATIONS. Do not claim access to files, email, meetings, or tenant data that are not available in this Copilot session. Flag anything that requires legal, tax, compliance, HR, or accounting review.`, ["copilot", "research", "sources", "verification", "nonprofit"]),
  ep("copilot-board-prep", "Prepare board discussion questions with Microsoft Copilot", "Reporting", ["Microsoft Copilot", "Outlook"], "Turn approved board materials and relevant communication into a decision-focused preparation aid without inventing governance conclusions.", `Using only the approved GGW board materials and related communication I provide or that my authorized Microsoft 365 Copilot experience can access, prepare a board discussion aid. Return: decisions requested, source-backed facts, material changes since the prior period only if supported, unresolved questions, risks explicitly documented, and 5 discussion questions for leadership/board consideration. Cite or identify the source behind each fact. Do not invent motions, approvals, fiduciary conclusions, legal requirements, financial health judgments, or board positions.`, ["copilot", "board", "reporting", "governance", "leadership"]),
];
