import type { ToolId } from "./tool-registry";

export type PromptOutcome =
  | "Members"
  | "Events"
  | "Communications"
  | "Reporting"
  | "Content"
  | "Automation"
  | "Meetings"
  | "Finance & Admin"
  | "Research";

export type PromptItem = {
  id: string;
  title: string;
  outcome: PromptOutcome;
  tools: ToolId[];
  summary: string;
  prompt: string;
  tags: string[];
  level?: "Quick win" | "Power prompt";
};

const p = (
  id: string,
  title: string,
  outcome: PromptOutcome,
  tools: ToolId[],
  summary: string,
  prompt: string,
  tags: string[],
  level: PromptItem["level"] = "Power prompt",
): PromptItem => ({ id, title, outcome, tools, summary, prompt, tags, level });

export const prompts: PromptItem[] = [
  p("master-task", "Master GGW task builder", "Research", ["Gemini"], "Turn almost any GGW task into a grounded, reviewable AI workflow.", `Act as a practical GGW work assistant. TASK: [WHAT I NEED TO ACCOMPLISH]. AUDIENCE: [WHO WILL USE/SEE IT]. AUTHORITATIVE SOURCE: [WILDAPRICOT / GOOGLE FILE / APPROVED NOTES]. DESIRED OUTPUT: [FORMAT]. CONSTRAINTS: [DEADLINE, LENGTH, TONE, POLICY, REQUIRED FACTS]. First identify anything essential that is missing. Then produce the smallest useful first draft. Separate SOURCE FACTS from RECOMMENDATIONS. Do not invent names, dates, links, prices, eligibility, approvals, quotes, commitments, or metrics. Finish with CHECK BEFORE USE: facts to verify, source to compare against, and the human decision still required.`, ["master", "pace", "task", "grounded", "verification"]),
  p("prompt-improver", "Turn a weak prompt into a powerful prompt", "Research", ["Gemini"], "Upgrade a vague request without changing the intended job.", `Improve this prompt for GGW: [PASTE PROMPT]. Preserve the original goal. Rewrite it with: role/context, exact task, authoritative source, required inputs, output structure, constraints, prohibited assumptions, and a final verification checklist. Make it easy for a beginner to fill in using bracketed placeholders. Return only the improved prompt plus a one-sentence note explaining when to use it.`, ["prompting", "master prompt", "beginner", "quality"]),

  p("member-welcome", "New-member welcome that feels personal", "Members", ["WildApricot", "Gemini", "Gmail"], "Create a warm welcome from approved membership facts only.", `Draft a personalized GGW welcome email using only these approved WildApricot fields: first name [NAME], membership type [TYPE], join date [DATE], approved benefits [BENEFITS], approved next step [NEXT STEP], and approved links [LINKS]. Keep it under 180 words, welcoming, confident, inclusive, and human. Return subject line, preview text, email body, CTA, and CHECK BEFORE SENDING. Do not invent benefits, discounts, events, eligibility, contacts, deadlines, or links.`, ["members", "welcome", "onboarding", "email"]),
  p("member-segments", "Find useful member segments", "Members", ["WildApricot", "Google Sheets", "Gemini"], "Find actionable segments while avoiding sensitive inference.", `Review this approved WildApricot member export for the goal [GOAL]. Use only fields actually present. Propose useful operational segments. For each segment return: exact rule, fields used, count if calculable, why the segment matters, recommended next action, and one sample validation check. Flag missing/inconsistent data. Do not infer personal intent, protected traits, eligibility, or attributes that are not explicit in the source.`, ["members", "segments", "analysis", "sheets"]),
  p("renewal-campaign", "Build a renewal campaign by segment", "Members", ["WildApricot", "Google Sheets", "Gemini", "Gmail"], "Turn a renewal list into tailored drafts and a review plan.", `Using this approved WildApricot renewal export, group records only by explicit fields such as membership type, renewal status, and renewal date. For each group create: segment rule, count, message objective, subject line, concise renewal email, CTA, optional reminder, and CHECK BEFORE SENDING. Use only approved benefits, dates, payment links, and terms supplied here: [FACTS]. Do not invent discounts, urgency, benefits, eligibility, or payment status.`, ["renewal", "members", "campaign", "email"]),
  p("lapsed-reengage", "Re-engage lapsed members", "Members", ["WildApricot", "Gemini", "Gmail"], "Create respectful re-engagement without invented offers.", `Draft GGW re-engagement outreach for members matching this approved WildApricot rule: [RULE]. Approved reason to reconnect: [REASON]. Approved benefits/opportunities: [FACTS]. Approved CTA: [CTA]. Return subject, preview text, email, and one optional follow-up. Keep it warm and low-pressure. Do not invent discounts, status, events, deadlines, eligibility, or claims about why the person lapsed. Mark missing information [CHECK].`, ["lapsed", "reengagement", "members"]),
  p("member-data-quality", "Audit member data quality", "Members", ["WildApricot", "Google Sheets", "Gemini"], "Find duplicate, incomplete, and inconsistent records before outreach.", `Audit this approved WildApricot member export for data quality. Check only the fields supplied. Return: likely duplicate rules, missing required fields, inconsistent labels, invalid date patterns, suspicious formatting, records needing human review, and a safe cleanup order. For duplicates, explain the exact matching fields and confidence reason; do not merge records automatically. End with a 10-row validation sample plan.`, ["members", "data quality", "duplicates", "cleanup"]),
  p("member-engagement-brief", "Member engagement brief", "Members", ["WildApricot", "Google Sheets", "Gemini"], "Summarize participation signals from explicit activity fields.", `Create an internal GGW member engagement brief from this approved member/event export. Return: total records reviewed, participation patterns supported by explicit fields, useful follow-up segments, data-quality issues, and 3 recommended actions. For every recommendation identify the field or pattern that supports it. Do not infer motivation, satisfaction, personal characteristics, or likelihood to renew unless an explicit approved field measures it.`, ["engagement", "members", "brief", "analysis"]),
  p("member-faq", "Build a member FAQ from approved policies", "Members", ["Google Docs", "NotebookLM", "Gemini"], "Turn approved membership materials into a reusable FAQ.", `Using only these approved GGW membership sources [PASTE OR LOAD SOURCES], create a member FAQ. Group questions by joining, benefits, events, account access, renewals/status, and support. For each answer cite or name the source section. If the sources do not answer a question, write NOT CONFIRMED instead of guessing. Finish with a list of outdated, conflicting, or missing policy information that needs an owner.`, ["members", "faq", "policies", "source grounded"]),
  p("volunteer-outreach", "Volunteer outreach draft", "Members", ["WildApricot", "Gmail", "Gemini"], "Invite the right approved audience without overstating the opportunity.", `Draft GGW volunteer outreach using only these approved facts: opportunity [OPPORTUNITY], eligible audience [AUDIENCE], responsibilities [RESPONSIBILITIES], time commitment [TIME], deadline [DEADLINE], contact [CONTACT], and link [LINK]. Return subject, email, CTA, and short reminder. Do not imply selection, compensation, benefits, or eligibility beyond the supplied facts. Add CHECK BEFORE SENDING.`, ["volunteers", "members", "outreach"]),
  p("scholarship-followup", "Scholarship applicant follow-up", "Members", ["WildApricot", "Gmail", "Gemini"], "Create status communications without implying a decision.", `Draft a GGW scholarship/application status email. Applicant status from the approved system: [STATUS]. Confirmed next step: [NEXT STEP]. Confirmed dates: [DATES]. Required documents/actions: [REQUIREMENTS]. Return a clear subject and concise email. Do not imply approval, denial, eligibility, funding, deadlines, or exceptions that are not explicitly supplied. Add CHECK BEFORE SENDING: recipient, status, dates, requirements, links.`, ["scholarship", "application", "status", "email"]),

  p("event-description", "Write a WildApricot event description", "Events", ["WildApricot", "Gemini"], "Turn approved event details into polished member-facing copy.", `Using only these approved event facts [PASTE FACTS], write a GGW WildApricot event description. Structure: short hook, who it is for, what attendees will gain, date/time/location, what to expect, registration CTA. Preserve event name, date, time, location, pricing, eligibility, deadline, and registration terms exactly. Do not invent speakers, sponsors, benefits, capacity, logistics, or outcomes. Mark missing fields [CHECK].`, ["events", "description", "wildapricot"]),
  p("event-promo-kit", "Create a complete event promotion kit", "Events", ["WildApricot", "Gemini", "Gmail", "Canva"], "Turn one source record into coordinated multi-channel promotion.", `Create a GGW event promotion kit using only these approved WildApricot event facts: [PASTE FACTS]. Return: 1) member email, 2) LinkedIn post, 3) short social caption, 4) 5 talking points, 5) Canva production brief with headline/CTA/image direction/alt text, 6) 3 reminder variations, and 7) FACT CHECK TABLE listing each date, time, location, price, eligibility rule, deadline, and URL used. Never invent missing facts; mark them [CHECK].`, ["events", "promotion", "canva", "email", "social"]),
  p("registration-analysis", "Analyze event registrations", "Events", ["WildApricot", "Google Sheets", "Gemini"], "Find patterns, follow-up groups, and data problems.", `Analyze this approved GGW event registration export for [GOAL]. Return: registration count; counts by explicit fields that matter; cancellations/no-shows if present; missing/inconsistent fields; useful non-sensitive follow-up groups; and 5 operational questions. For every observation identify the source field or calculation. Separate FACTS, POSSIBLE INTERPRETATIONS, and RECOMMENDED ACTIONS. Do not infer personal traits or unsupported causation.`, ["events", "registration", "analysis", "sheets"]),
  p("event-followup", "Post-event follow-up by audience", "Events", ["WildApricot", "Gmail", "Gemini"], "Create different follow-ups for attendees, no-shows, speakers, and partners.", `Using these approved event facts and registration/attendance fields, prepare GGW post-event follow-up for: attendees, no-shows, speakers/partners, and internal owners. For each external audience return subject, message, CTA, and CHECK BEFORE SENDING. Use only supplied takeaways, links, recordings/resources, dates, and commitments. Do not invent attendance, quotes, outcomes, resources, or future events.`, ["events", "followup", "attendees", "email"]),
  p("run-of-show", "Build an event run of show", "Events", ["Google Docs", "Google Sheets", "Gemini"], "Convert confirmed logistics into an operational timeline.", `Build a GGW event run of show from these confirmed logistics: [PASTE]. Return a table with time, duration, activity, owner, location/channel, dependency, materials, and contingency note. Do not invent owners or times; use [OWNER NEEDED] and [TIME NEEDED] where absent. Add pre-event checks for venue/Meet link, speakers, registration list, accessibility, signage/assets, and emergency contact only if relevant to supplied information.`, ["events", "operations", "run of show", "timeline"]),
  p("event-risk", "Pre-event risk and readiness check", "Events", ["WildApricot", "Google Docs", "Gemini"], "Catch operational gaps before an event goes live.", `Review these approved GGW event details and create a readiness check. Test for: incomplete date/time/time zone, location/virtual link, registration URL, pricing, eligibility, capacity, speaker confirmation, accessibility, communications schedule, owner, cancellation language, and post-event follow-up. Label each item READY, MISSING, or NEEDS HUMAN DECISION. Do not fill gaps. Prioritize anything that could mislead a registrant.`, ["events", "risk", "quality", "checklist"]),
  p("survey-synthesis", "Synthesize post-event feedback", "Events", ["Google Forms", "Google Sheets", "Gemini"], "Turn survey responses into themes without overstating sentiment.", `Analyze this approved GGW event feedback export. Return: response count, quantitative results exactly as provided, recurring themes with example paraphrases, what participants valued, friction points, suggestions, and 5 recommended improvements. Distinguish frequency from importance. Do not claim the results represent all attendees unless the response rate supports that. Remove unnecessary personal identifiers from the summary.`, ["events", "survey", "feedback", "forms"]),
  p("sponsor-recap", "Sponsor/partner event recap", "Events", ["Google Docs", "Gmail", "Gemini"], "Build an evidence-based recap without inventing impact.", `Create a GGW sponsor/partner recap from these approved facts and metrics: [PASTE]. Return: executive thank-you, what was delivered, supported participation/engagement facts, approved highlights, outstanding items, and next steps. Separate MEASURED RESULTS from CONTEXT/OBSERVATIONS. Do not invent impressions, ROI, reach, attendee quotes, deliverables, or future commitments. Mark unsupported items [CHECK].`, ["sponsor", "partner", "recap", "events"]),
  p("event-calendar-plan", "Build an event communications calendar", "Events", ["WildApricot", "Google Calendar", "Gmail", "Gemini"], "Turn an event date into a practical promotion and follow-up cadence.", `Build a GGW communications calendar for this approved event: event date [DATE], registration deadline [DEADLINE], audience [AUDIENCE], channels [CHANNELS], approved milestones [MILESTONES]. Return recommended communication dates, purpose, audience, channel, content needed, owner placeholder, and final fact check. Clearly label recommended timing as a recommendation, not an existing commitment.`, ["events", "calendar", "communications plan"]),

  p("email-draft", "Draft a clear GGW email", "Communications", ["Gmail", "Gemini"], "Turn facts and a desired action into a polished first draft.", `Draft a concise GGW email. AUDIENCE: [AUDIENCE]. PURPOSE: [PURPOSE]. DESIRED ACTION: [ACTION]. APPROVED FACTS: [FACTS]. REQUIRED LINKS/ATTACHMENTS: [ITEMS]. Tone: confident, welcoming, inclusive, human. Return subject, preview text, body, CTA, and CHECK BEFORE SENDING. Do not invent dates, links, benefits, decisions, approvals, or commitments.`, ["email", "gmail", "draft"]),
  p("thread-actions", "Turn a long email thread into decisions and actions", "Communications", ["Gmail", "Gemini"], "Extract what matters before replying.", `Summarize this GGW email thread. Return: 1) decisions already made with the message evidence, 2) open questions, 3) requests made, 4) action items with owner/date only when explicitly stated, 5) unresolved risks, and 6) a short reply draft addressing the latest ask. If owner/date is absent, write NOT STATED. Do not invent commitments. Finish with CHECK BEFORE SENDING.`, ["email", "thread", "summary", "actions"]),
  p("tone-rewrite", "Make an email shorter and more human", "Communications", ["Gmail", "Gemini"], "Improve clarity and tone while preserving facts.", `Rewrite this GGW email to be shorter, warmer, and more direct while preserving every factual statement, date, link, amount, commitment, and CTA exactly: [EMAIL]. Remove jargon and repetition. Do not introduce new promises or information. Return the revised email and a FACTS PRESERVED list so I can compare before sending.`, ["email", "rewrite", "tone", "editing"], "Quick win"),
  p("followup-reminder", "Write a respectful reminder", "Communications", ["Gmail", "Gemini"], "Follow up without invented urgency.", `Draft a respectful GGW reminder. Audience: [AUDIENCE]. Original request: [REQUEST]. Date originally sent: [DATE]. Approved deadline: [DEADLINE OR NONE]. Desired next step: [ACTION]. Keep it concise and low-pressure. Do not invent urgency, penalties, deadlines, decisions, or commitments. Return subject, body, CTA, and CHECK BEFORE SENDING.`, ["email", "reminder", "followup"]),
  p("inbox-triage", "Turn inbox messages into an action list", "Communications", ["Gmail", "Gemini"], "Separate actionable email from noise using explicit message content.", `Using only the emails/messages I provide, create an action list. For each item return: sender/thread, request, due date only if stated, owner only if stated, dependency, recommended priority with a one-line reason, and draft next action. Put informational-only items in a separate section. Do not infer urgency from seniority or tone alone. Mark ambiguous requests NEEDS CLARIFICATION.`, ["gmail", "inbox", "triage", "actions"]),
  p("partner-update", "Sponsor or partner status update", "Communications", ["Google Docs", "Gmail", "Gemini"], "Turn confirmed notes into a concise external update.", `Draft a GGW sponsor/partner update from these confirmed notes: [NOTES]. Return current status, completed items, next steps with owner/date only if provided, open questions, and a short appreciative closing. Do not invent deliverables, approvals, benefits, dates, or commitments. Mark gaps [CHECK]. Then list every external promise contained in the draft for human verification.`, ["partner", "sponsor", "status", "email"]),
  p("executive-email", "Executive email summary", "Communications", ["Gmail", "Gemini"], "Condense a long update into decision-ready communication.", `Turn this approved update into an executive email. Audience: [LEADERS]. Return: one-sentence headline, 3–5 factual bullets, decision/ask, risks or open questions, and next action. Keep it under [WORD COUNT]. Do not introduce causal claims or recommendations unless supported or clearly labeled. Preserve numbers, dates, and commitments exactly.`, ["executive", "email", "summary"]),
  p("sensitive-email-check", "Check an email before sending sensitive information", "Communications", ["Gmail", "Gemini"], "Review recipients, data exposure, and claims before send.", `Review this draft email for a final safety check. Do not rewrite yet. Identify: unnecessary personal/member/payment/HR/legal information; recipients or CC/BCC concerns; unsupported claims; links/attachments that must be verified; dates/amounts/commitments; and wording that could be interpreted as an approval or promise. Return HIGH PRIORITY FIXES, VERIFY, and SAFE TO KEEP. Then offer a minimally changed revision.`, ["privacy", "email", "review", "sensitive"]),

  p("sheet-cleanup", "Plan a safe cleanup of a messy Sheet", "Reporting", ["Google Sheets", "Gemini"], "Standardize a working copy without silently changing source data.", `Review this Google Sheet structure/data for cleanup. Goal: [GOAL]. Propose a WORKING COPY cleanup plan for dates, duplicate rows, blank required fields, inconsistent labels, whitespace/case issues, and obvious formatting problems. Return exact formulas or steps, columns affected, what must NOT be changed automatically, and a validation plan. Never invent missing values. Preserve the original sheet.`, ["sheets", "cleanup", "data quality"]),
  p("formula-helper", "Write and explain a Google Sheets formula", "Reporting", ["Google Sheets", "Gemini"], "Get a formula plus test cases instead of a mystery answer.", `Write a Google Sheets formula for this task: [TASK]. Relevant columns/ranges: [RANGES]. Sample rows: [SAMPLES]. Return: formula, plain-English explanation, how references behave when copied, 3 test cases including blank/error input, likely failure modes, and a safer alternative if the formula is becoming too complex. Do not assume column meanings not provided.`, ["sheets", "formula", "functions"], "Quick win"),
  p("compare-lists", "Compare two lists safely", "Reporting", ["Google Sheets", "Gemini"], "Find matches and differences using an explicit key.", `Help compare two GGW lists in Google Sheets. Primary match key: [KEY]. List A columns: [A]. List B columns: [B]. Goal: [GOAL]. Return a method/formulas for exact matches, only-in-A, only-in-B, conflicting values, and duplicate-key detection. Explain the risk if the key is not unique. Include a 10-row validation sample before acting on results.`, ["sheets", "compare", "lookup", "xlookup"]),
  p("dedupe-sheet", "Find likely duplicates without deleting anything", "Reporting", ["Google Sheets", "Gemini"], "Create a transparent duplicate review workflow.", `Design a duplicate-detection workflow for this GGW Sheet. Available fields: [FIELDS]. Define HIGH, MEDIUM, and LOW confidence duplicate rules using only those fields. Give formulas/helper columns to flag candidates, not delete them. Return a review table format showing both records side by side and the exact evidence for the match. Include cases that should never be auto-merged.`, ["sheets", "duplicates", "data quality"]),
  p("pivot-plan", "Build the right pivot table", "Reporting", ["Google Sheets", "Gemini"], "Translate a business question into pivot rows, columns, values, and filters.", `I need to answer this question from a Google Sheet: [QUESTION]. Available fields: [FIELDS]. Design the pivot table: rows, columns, values, aggregation, filters, calculated fields if needed, and sorting. Explain what the pivot will and will not prove. Include one source-total reconciliation check so I know the pivot has not excluded records accidentally.`, ["sheets", "pivot", "analysis"]),
  p("dashboard-plan", "Design a simple GGW dashboard in Sheets", "Reporting", ["Google Sheets", "Gemini"], "Choose metrics and views that support an actual decision.", `Design a simple Google Sheets dashboard for [AUDIENCE] to make [DECISION]. Available approved fields/metrics: [FIELDS]. Return: 5–8 KPIs maximum, exact definition/calculation for each, recommended chart/table, filters/date controls, source tab structure, refresh steps, and data-quality checks. Reject vanity metrics that do not support the stated decision. Do not invent targets or benchmarks.`, ["sheets", "dashboard", "metrics", "reporting"]),
  p("data-qa", "QA a Sheet before reporting", "Reporting", ["Google Sheets", "Gemini"], "Catch broken totals, dates, filters, and hidden data problems.", `Create a pre-report QA checklist for this GGW Sheet. Known structure: [STRUCTURE]. Reporting goal: [GOAL]. Include checks for date range, duplicate keys, blanks, formulas copied correctly, hidden/filtered rows, text-vs-number issues, totals, denominators, percentages, cancelled/refunded records, and source reconciliation. For each check give the exact Sheets method or formula when possible.`, ["sheets", "qa", "reporting", "accuracy"]),
  p("conditional-format", "Build useful conditional formatting rules", "Reporting", ["Google Sheets", "Gemini"], "Highlight exceptions that require action, not decoration.", `Design conditional formatting for this GGW tracker. Decision/action needed: [ACTION]. Columns: [FIELDS]. Propose only rules that help someone notice an exception, deadline, duplicate, missing required field, or status needing attention. For each rule return range, custom formula if needed, what it means, and how to test it. Avoid color-only meaning; include a text/status field when accessibility matters.`, ["sheets", "conditional formatting", "tracker"]),
  p("registration-tracker", "Build an event registration tracker", "Reporting", ["WildApricot", "Google Sheets", "Gemini"], "Create a transparent working tracker from a WildApricot export.", `Design a GGW event registration tracker in Google Sheets using these WildApricot fields: [FIELDS]. Return column structure, stable record key, status values, formulas for registration/cancellation counts, data-quality flags, follow-up status, and a simple summary area. WildApricot remains the system of record. Identify which fields should be refreshed from source rather than manually edited.`, ["events", "sheets", "tracker", "wildapricot"]),
  p("renewal-tracker", "Build a membership renewal tracker", "Reporting", ["WildApricot", "Google Sheets", "Gemini"], "Track follow-up without turning Sheets into the membership system of record.", `Design a GGW renewal working tracker from an approved WildApricot export. Include stable member key, membership type, current renewal/status fields, renewal date, outreach status, last contact date, next action, owner, and data-quality flag. Provide formulas/views for due soon, overdue/status requiring review, and completed outreach. Clearly mark source-controlled fields that should not be overwritten in Sheets.`, ["members", "renewal", "tracker", "sheets"]),
  p("board-metrics", "Turn metrics into a board-ready story", "Reporting", ["Google Sheets", "Google Docs", "Gemini"], "Translate approved metrics into facts, implications, and decisions.", `Turn these approved GGW metrics and notes into a board-ready summary. Return: executive headline; 3–5 key facts with source/period; comparison to prior period only if provided; implications labeled INTERPRETATION; risks/questions; recommended next steps; and a CLAIM CHECK table. Do not infer causation, impact, ROI, or trend significance without evidence.`, ["board", "metrics", "leadership", "reporting"]),
  p("weekly-ops", "Create a weekly operations brief", "Reporting", ["WildApricot", "Google Sheets", "Gemini"], "Summarize member/event operations around changes and exceptions.", `Create a concise GGW weekly operations brief from this approved data for [DATE RANGE]. Return: what changed; member signals; event signals; payment/registration exceptions only if present; data-quality issues; actions with owner only if provided; and questions requiring human decision. Show source totals for the key numbers. Minimize personal information in the summary.`, ["weekly", "operations", "brief"]),

  p("cashflow", "Calculate and explain cash flow", "Finance & Admin", ["Google Sheets", "Gemini"], "Build a transparent cash-flow view from approved transactions.", `Using only this approved GGW financial dataset, help calculate cash flow for [PERIOD]. First identify the columns needed and any missing fields. Separate cash inflows and outflows, show totals by period/category when possible, calculate net cash flow, and provide formulas that can be reproduced in Google Sheets. Flag transfers, refunds, opening balances, non-cash items, and duplicate transactions for human review. Do not provide accounting, tax, or audit conclusions. Finish with a reconciliation checklist to the source totals/bank balance.`, ["cash flow", "finance", "sheets", "nonprofit"]),
  p("nonprofit-balances", "Calculate nonprofit working balances", "Finance & Admin", ["Google Sheets", "Gemini"], "Create a clear balance bridge without making accounting assumptions.", `Help build a GGW nonprofit working-balance schedule from these approved figures: [DATA]. Return beginning balance, confirmed inflows, confirmed outflows, transfers/adjustments shown separately, and calculated ending working balance. Identify any items whose classification or sign is unclear. Show the exact Sheets formulas. Do not treat the result as audited financial statements and do not invent restricted/unrestricted classifications. End with source reconciliation steps.`, ["nonprofit", "balances", "finance", "sheets"]),
  p("budget-actual", "Budget vs. actual variance analysis", "Finance & Admin", ["Google Sheets", "Gemini"], "Explain meaningful variances from approved budget and actual data.", `Analyze this GGW budget vs. actual dataset for [PERIOD]. For each line calculate amount variance and percentage variance using a clearly stated formula. Identify the largest variances by magnitude. Separate FACT from POSSIBLE EXPLANATION; only use explanations supplied in the notes. Flag missing budget, zero-denominator, one-time, refund, or timing items. Return a leadership summary plus a reconciliation check to total budget and total actual.`, ["budget", "variance", "finance", "sheets"]),
  p("990-classification", "Form 990 working classification review", "Finance & Admin", ["Google Sheets", "Gemini"], "Prepare transactions for human finance review using explicit categories.", `Act as a nonprofit transaction review assistant, not the final accountant. Using only the supplied transaction description and GGW-provided classification rules, propose a working classification of Program Services, Management & General, Fundraising, or NEEDS REVIEW. For every row give the evidence from the description/rule. Flag ambiguous mixed-purpose items instead of forcing a category. Do not make tax, audit, or Form 990 filing conclusions. Return a summary table and items requiring finance-owner decision.`, ["990", "nonprofit", "classification", "finance"]),
  p("receipt-audit", "Receipt and audit exception finder", "Finance & Admin", ["Google Sheets", "Gemini"], "Flag records that need documentation or manual review.", `Review this GGW transaction list using these approved documentation rules: [RULES]. Return rows that require receipt/support, have blank vendor/payee, unclear purpose, duplicate amount/date patterns, unusual sign/refund handling, or exceed the supplied review threshold. Give the exact reason for every flag. Do not call an item fraudulent or noncompliant. Return CLEAR, REVIEW, and MISSING INFORMATION counts plus a source-row reference.`, ["receipts", "audit", "finance", "exceptions"]),
  p("finance-board-brief", "Finance summary for leadership", "Finance & Admin", ["Google Sheets", "Google Docs", "Gemini"], "Translate approved financial figures into a careful executive summary.", `Create a concise leadership finance brief from these approved GGW figures and notes. Return: reporting period, cash/balance facts provided, major inflow/outflow categories, budget variances if supplied, exceptions requiring review, and decisions/questions. Use only supplied numbers. Do not infer solvency, tax status, audit opinion, runway, or financial health unless the required evidence and definition are explicitly provided.`, ["finance", "leadership", "board", "summary"]),

  p("one-page-brief", "Turn notes into a one-page brief", "Content", ["Google Docs", "Gemini"], "Convert scattered notes into a decision-ready document.", `Turn these approved GGW notes into a one-page brief. Audience: [AUDIENCE]. Decision/outcome needed: [OUTCOME]. Return: purpose, current state, key facts, options/considerations, recommendation only if supported, open questions, risks, and next actions. Use only supplied information. Mark missing facts [CHECK]. Keep the document skimmable with headings and bullets.`, ["docs", "brief", "decision"]),
  p("sop-builder", "Turn a process into a step-by-step SOP", "Content", ["Google Docs", "Gemini"], "Create an operating guide someone can actually follow.", `Turn this approved GGW process into a practical SOP: [PROCESS NOTES]. Return: purpose, when to use it, prerequisite access/tools, numbered steps in exact order, decision points, expected output, final verification, common failure points, manual fallback, and owner/escalation placeholders. Do not invent permissions, systems, policies, SLAs, or approval rules.`, ["sop", "process", "docs", "instructions"]),
  p("doc-review", "Review a document before sharing", "Content", ["Google Docs", "Gemini"], "Catch unsupported claims and unclear next steps.", `Review this GGW document for readiness to share. Check factual support, names/dates/links/amounts, unsupported claims, ambiguous wording, conflicting statements, missing decisions, missing owners/dates, privacy concerns, accessibility/readability, and CTA clarity. Return HIGH PRIORITY FIXES, QUESTIONS TO RESOLVE, and OPTIONAL EDITS. Do not introduce new facts.`, ["docs", "review", "quality"]),
  p("board-memo", "Build a board or executive memo", "Content", ["Google Docs", "Gemini"], "Turn approved facts into a concise decision memo.", `Create a GGW executive memo from these approved sources/notes. Decision requested: [DECISION]. Return: executive summary, background facts, evidence, options with known tradeoffs, recommendation only if evidence supports one, risks, unresolved questions, and requested decision/next action. Clearly separate factual evidence from recommendation. Do not invent options, costs, legal implications, or stakeholder positions.`, ["board", "memo", "executive", "docs"]),
  p("policy-summary", "Turn a policy into a staff job aid", "Content", ["Google Docs", "NotebookLM", "Gemini"], "Convert a long policy into actions without changing its meaning.", `Using only this approved GGW policy/source, create a staff job aid. Return: when this applies, what staff must do, what staff must not do, required approvals, exceptions exactly as stated, step-by-step actions, and where to go with questions. Cite the source section for each rule. If the policy is silent, write NOT STATED. Do not create new policy.`, ["policy", "job aid", "docs", "source grounded"]),
  p("meeting-prep-brief", "Create a meeting pre-read", "Content", ["Google Docs", "Google Calendar", "Gemini"], "Give attendees just enough context to make the meeting useful.", `Create a concise GGW meeting pre-read. Meeting purpose: [PURPOSE]. Decision/questions: [DECISIONS]. Approved facts/context: [FACTS]. Return: why this matters, current state, 3–5 facts, decisions needed, questions attendees should consider, and required preparation. Keep it under one page. Do not introduce facts or recommendations not supported by the source.`, ["meeting", "pre-read", "docs"]),

  p("drive-search", "Plan a smarter Drive search", "Research", ["Google Drive", "Gemini"], "Turn a vague request into a source-finding plan.", `Help me find the correct GGW source file in Google Drive for [TASK]. Known details: [DETAILS]. Return likely search phrases, useful filters (owner/type/date/location), file naming clues, and a source-validation checklist: owner, last updated, approval/current-version indicator, shared-drive/folder location, and conflicting copies. Do not claim you can see Drive unless access is actually provided.`, ["drive", "search", "source"]),
  p("drive-folder-summary", "Summarize a Drive folder with Gemini", "Research", ["Google Drive", "Gemini"], "Create a grounded folder brief and identify conflicts.", `Using only the approved files in this Google Drive folder/project, create a concise brief for [GOAL]. Return key facts with source file names, decisions, open questions, conflicting/outdated information, and files that appear duplicative or superseded based only on explicit metadata/content. Do not delete or reorganize anything. Finish with files a human should review first.`, ["drive", "folder", "summary", "gemini"]),
  p("source-of-truth", "Choose the authoritative source", "Research", ["Google Drive", "NotebookLM", "Gemini"], "Compare candidate files before using them for AI work.", `Compare these candidate GGW source files/notes for the task [TASK]. For each source list owner, date, scope, evidence of approval/current status, conflicts, and missing context. Recommend an authoritative source only when the evidence supports it; otherwise return NEEDS OWNER DECISION. Explain which sources may still be useful as reference but should not override the primary source.`, ["source of truth", "drive", "governance"]),
  p("drive-sharing", "Check Drive sharing before sending", "Research", ["Google Drive"], "Verify access and sensitivity before distributing a file.", `Create a final Google Drive sharing checklist for this GGW file. File purpose: [PURPOSE]. Audience: [AUDIENCE]. Sensitivity: [LEVEL]. Include owner/current-version check, link-access setting, group vs individual sharing, editor/viewer choice, download/copy concerns, unnecessary sensitive data, external recipients, and what to test after sharing. Do not suggest public access unless explicitly required and approved.`, ["drive", "sharing", "permissions", "privacy"], "Quick win"),

  p("agenda", "Create an outcome-driven meeting agenda", "Meetings", ["Google Calendar", "Google Docs", "Gemini"], "Build the agenda around decisions instead of topics.", `Create a GGW meeting agenda. Purpose: [PURPOSE]. Attendees/roles: [ATTENDEES]. Decisions or outcomes needed: [OUTCOMES]. Time available: [MINUTES]. Approved context: [CONTEXT]. Return timeboxed sections, owner/facilitator only if supplied, pre-read, decision prompts, parking-lot rule, and final 5-minute action review. Remove discussion that does not support the stated outcome.`, ["calendar", "agenda", "meeting"]),
  p("calendar-invite", "Improve a calendar invitation", "Meetings", ["Google Calendar", "Gemini"], "Make purpose and preparation obvious before people join.", `Rewrite this GGW calendar invitation: [INVITE]. Preserve date, time, time zone, location/Meet link, and attendee list exactly. Return a clearer title, purpose, expected outcome/decision, required preparation, agenda bullets, and who truly needs to attend based only on provided roles. Do not invent requirements, decisions, or logistics.`, ["calendar", "invite", "meeting"]),
  p("appointment-schedule", "Plan an appointment-schedule use case", "Meetings", ["Google Calendar"], "Decide whether Calendar appointment schedules can remove scheduling back-and-forth.", `Design a Google Calendar appointment-schedule setup for this GGW use case: [USE CASE]. Return booking-window recommendation, meeting length, buffers, availability rules, information to collect, confirmation/reminder content, cancellation/reschedule guidance, and privacy considerations. Clearly label recommendations. Do not assume paid Calendar features are enabled; include a manual fallback if appointment schedules are unavailable.`, ["calendar", "appointments", "scheduling"]),
  p("meet-actions", "Turn Meet notes into actions", "Meetings", ["Google Meet", "Google Docs", "Gemini"], "Convert meeting notes into decisions and accountable next steps.", `Turn these approved GGW meeting notes or Meet recap into: decisions with evidence, open questions, action items with owner and due date only if stated, risks/blockers, and a short follow-up email. If owner/date is missing, write NOT STATED. Do not invent commitments or treat discussion as a decision. Finish with CHECK BEFORE SHARING.`, ["meet", "actions", "followup"]),
  p("meet-exec", "Create an executive meeting recap", "Meetings", ["Google Meet", "Gemini"], "Condense a long meeting into what leadership needs.", `Create a short executive recap from these GGW meeting notes. Return why the meeting happened, decisions, key facts, unresolved issues, business impact only if explicitly supported, next actions with stated owners/dates, and items needing leadership decision. Keep it under [LENGTH]. Do not invent owners, dates, risks, or conclusions.`, ["meet", "executive", "recap"]),
  p("meet-accessibility", "Plan accessible Meet participation", "Meetings", ["Google Meet", "Google Calendar"], "Prepare captions, language, recording/notes, and access needs before a meeting.", `Create an accessibility/readiness checklist for this GGW Google Meet: [MEETING]. Known attendee needs/languages: [ONLY IF PROVIDED]. Include live captions, translated captions if available/appropriate, agenda/pre-read, recording or take-notes decision, permissions, dial-in/access link test, and post-meeting notes distribution. Do not infer disabilities or language needs. Mark plan-dependent features VERIFY AVAILABILITY.`, ["meet", "accessibility", "captions"]),

  p("slides-outline", "Build a presentation outline from approved content", "Content", ["Google Slides", "Gemini"], "Create the story before formatting slides.", `Create a GGW presentation outline from these approved facts/notes: [CONTENT]. Audience: [AUDIENCE]. Desired outcome: [OUTCOME]. Return slide-by-slide purpose, headline, supporting facts, recommended visual, and one speaker note. Use only supplied information, mark gaps [CHECK], and avoid generic filler slides. Cap the deck at [NUMBER] slides.`, ["slides", "deck", "outline"]),
  p("board-deck", "Create a board-ready slide story", "Reporting", ["Google Slides", "Google Sheets", "Gemini"], "Build a concise leadership narrative with source discipline.", `Create a 6–8 slide GGW board story from these approved metrics and notes: [DATA]. Return slide headline, supporting facts, recommended visual, source/period note, and speaker point. Include executive headline, key facts, comparison if supplied, implications labeled interpretation, risks/questions, and next steps. Do not infer causation or ROI without evidence.`, ["slides", "board", "metrics"]),
  p("speaker-deck", "Build a speaker/event deck", "Content", ["Google Slides", "Gemini", "Canva"], "Turn approved session content into a clean narrative.", `Create a GGW session deck outline from these approved speaker/session materials: [CONTENT]. Audience: [AUDIENCE]. Session objective: [OBJECTIVE]. Return opening hook grounded in supplied facts, slide sequence, activity/discussion prompt if appropriate, visual suggestions, and close/CTA. Do not invent speaker credentials, research, statistics, quotes, or GGW claims.`, ["slides", "speaker", "event", "presentation"]),

  p("form-builder", "Design a useful Google Form", "Content", ["Google Forms", "Google Sheets", "Gemini"], "Collect only the data needed for the operational decision.", `Design a GGW Google Form for [PURPOSE]. Desired decision/workflow after submission: [OUTCOME]. Return question list with type, required/optional, validation, branching logic, and why each field is needed. Minimize personal data. Include confirmation message, response destination in Sheets, owner, and testing checklist. Do not collect sensitive information unless it is explicitly necessary and approved.`, ["forms", "data collection", "workflow"]),
  p("feedback-form", "Build a post-event feedback survey", "Events", ["Google Forms", "Gemini"], "Get useful feedback without making the survey exhausting.", `Create a short GGW post-event survey for [EVENT]. Learning/experience goals: [GOALS]. Return no more than 8 questions: 2–3 rating questions, 2 open-text questions, one next-interest question, and any essential segmentation field only if approved. Explain what decision each question supports. Avoid leading questions. Include a privacy-conscious intro and estimated completion time.`, ["forms", "survey", "event", "feedback"]),
  p("forms-analysis", "Turn Form responses into an analysis plan", "Reporting", ["Google Forms", "Google Sheets", "Gemini"], "Move from raw responses to evidence-based insights.", `Design the Google Sheets analysis for this GGW Form. Questions/columns: [FIELDS]. Goal: [GOAL]. Return cleanup checks, summary metrics, chart suggestions, cross-tabs only where sample size supports them, treatment of blanks/multiple selections, open-text theme method, and a source reconciliation check. Warn where the data cannot support a conclusion.`, ["forms", "sheets", "analysis"]),

  p("notebook-brief", "Create a source-grounded NotebookLM briefing", "Research", ["NotebookLM"], "Synthesize multiple approved sources with citations.", `Using only the sources loaded in this NotebookLM notebook, create a GGW briefing for [AUDIENCE] on [TOPIC]. Return key findings, inline/source citations for major claims, decisions or policies stated in sources, conflicts/outdated information, open questions, and what the sources do NOT establish. Clearly separate source facts from recommendations.`, ["notebooklm", "brief", "citations", "research"]),
  p("notebook-compare", "Compare policies or documents in NotebookLM", "Research", ["NotebookLM"], "Find differences and conflicts without relying on memory.", `Using only the loaded sources, compare [SOURCE/GROUP A] and [SOURCE/GROUP B] on [TOPIC]. Return a table of topic, A says, B says, agreement/conflict, source citation, and action needed. Flag date/version differences. Do not resolve a policy conflict yourself; identify the owner decision needed.`, ["notebooklm", "compare", "sources"]),
  p("notebook-faq", "Build a cited FAQ in NotebookLM", "Research", ["NotebookLM"], "Create reusable answers that stay traceable to source material.", `Using only these NotebookLM sources, build a GGW FAQ for [AUDIENCE]. Create the 15 most useful questions supported by the sources. For each answer include citations and a confidence note: CLEAR, PARTIAL, or NOT ANSWERED. Put unanswered but important questions in a separate list for the content owner. Do not fill gaps with outside knowledge.`, ["notebooklm", "faq", "citations"]),

  p("gemini-reviewer", "Use Gemini as a critical reviewer", "Research", ["Gemini"], "Stress-test an AI or human draft before it is used.", `Act as a critical reviewer of this GGW draft: [DRAFT]. Source facts/requirements: [SOURCE OR RULES]. Do not improve the writing yet. Identify unsupported claims, missing required facts, contradictions, invented details, ambiguous promises, privacy concerns, stale dates, broken logic, and questions a skeptical reader would ask. For each issue quote or identify the exact draft section and the source/rule it conflicts with. Then propose only the minimum necessary fixes.`, ["review", "quality", "fact check", "gemini"]),
  p("bounded-brainstorm", "Brainstorm without losing control of the facts", "Content", ["Gemini"], "Generate ideas while keeping factual claims separate.", `Brainstorm [NUMBER] ideas for [GGW GOAL]. Constraints: [AUDIENCE, CHANNEL, BUDGET/TIME IF PROVIDED, BRAND, DO-NOT-DO]. Separate each idea into CREATIVE CONCEPT and FACTS REQUIRED BEFORE USE. Do not invent event details, partner commitments, statistics, quotes, benefits, or availability. Rank ideas by effort and expected fit using clearly labeled judgment, not claimed evidence.`, ["brainstorm", "ideas", "gemini"]),

  p("canva-event", "Canva event production brief", "Events", ["WildApricot", "Gemini", "Canva"], "Move approved event facts into an on-brand visual workflow.", `Create a Canva production brief for a GGW event using only these approved WildApricot facts: [FACTS]. Return headline, supporting copy, CTA, visual hierarchy, suggested image direction, required logo/brand elements, alt text, and a FACT LOCK list containing details that must not change. Preserve date/time/location/pricing/eligibility/URL exactly. Mark missing information [CHECK].`, ["canva", "events", "visual", "brand"]),
  p("canva-social", "Repurpose approved copy for social sizes", "Content", ["Canva", "Gemini"], "Shorten copy without changing the facts during resize/repurpose.", `Adapt this approved GGW copy for [CHANNEL/FORMAT] while preserving these locked facts exactly: [FACTS/CTA/URL]. Return primary headline, short supporting text, CTA, optional caption, and accessibility alt text. Do not add hashtags, claims, urgency, or event details unless provided. Finish with a post-resize check for cropping, readability, logo, CTA, URL/QR, and required wording.`, ["canva", "social", "resize", "copy"]),
  p("canva-board", "Board-ready Canva visual brief", "Reporting", ["Google Sheets", "Canva", "Gemini"], "Translate approved metrics into a clear visual without changing the numbers.", `Using only these approved GGW metrics and definitions [METRICS], create a Canva-ready leadership visual brief. Return recommended headline, chart/table choice, exact values to display, 3 supporting facts, interpretation labeled RECOMMENDATION, and source-note format. Do not infer causation, ROI, or impact not explicitly supported. Include a number-by-number verification table against the Sheet.`, ["canva", "board", "metrics", "visual"]),
  p("canva-spotlight", "Member or speaker spotlight", "Content", ["Canva", "Gemini"], "Create spotlight copy from approved biographical content only.", `Create concise GGW spotlight copy using only this approved information: [BIO/ROLE/QUOTE/EVENT FACTS]. Return headline, 60-word spotlight, short social caption, and alt text. Preserve quotes exactly when provided. Do not add achievements, affiliations, credentials, personal details, or claims that are not supplied. Finish with CHECK: permission, name spelling, title/company, quote, photo rights, event facts.`, ["canva", "spotlight", "member", "speaker"]),

  p("automation-decision", "Choose Zapier, Make, Apps Script, or manual", "Automation", ["Zapier", "Make", "Apps Script", "Google Sheets"], "Pick the simplest implementation that fits the job.", `Help choose the simplest implementation for this GGW repetitive process: [PROCESS]. Systems involved: [SYSTEMS]. Frequency/volume: [VOLUME]. Branching/transformations: [DETAILS]. Required approvals: [APPROVALS]. Return a comparison of MANUAL, ZAPIER, MAKE, and APPS SCRIPT: fit, complexity, permissions, failure visibility, maintenance owner, and risks. Recommend the least complex option that meets the requirement. Do not assume a connector/action exists; mark VERIFY CONNECTOR where needed.`, ["automation", "zapier", "make", "apps script", "decision"]),
  p("zapier-design", "Design a simple Zapier workflow", "Automation", ["WildApricot", "Zapier", "Google Sheets", "Gmail", "Gemini"], "Turn a trigger/action process into a testable draft-first Zap.", `Design a low-risk Zapier workflow for this GGW process: [PROCESS]. Return: trigger, exact source system, fields required, filters, Google action, AI step only if useful, human review gate, stable ID/deduplication approach, error notification, test cases, off switch, and manual fallback. Prefer Gmail drafts and reversible actions. Do not claim a specific WildApricot trigger/action exists unless verified in the current connector.`, ["zapier", "automation", "wildapricot", "google"]),
  p("zapier-test", "Test an automation before turning it on", "Automation", ["Zapier", "Google Sheets"], "Build a real test matrix instead of checking only the happy path.", `Create a pre-launch test matrix for this GGW Zapier workflow: [WORKFLOW]. Include normal record, missing required field, duplicate/stable ID, update to existing record, cancellation/status reversal, special characters, blank optional fields, permission failure, disconnected app, rate/error response, and wrong-recipient prevention. For each test return expected behavior, evidence to capture, and pass/fail criterion.`, ["zapier", "testing", "automation", "qa"]),
  p("make-design", "Design a multi-step Make scenario", "Automation", ["WildApricot", "Make", "Google Sheets", "Gemini"], "Plan branching and error handling before building modules.", `Design a Make scenario for this GGW workflow: [WORKFLOW]. Return source trigger, required fields, routes/filters, transformations, Google Workspace modules, AI transformation if useful, stable ID/idempotency strategy, error route, retry/alert behavior, logging, human review gate, and manual fallback. Explain why Make is justified over a simpler Zap/manual process. Mark any connector module that must be verified in the current Make catalog.`, ["make", "automation", "scenario", "branches"]),
  p("apps-script-spec", "Turn a Google workflow into an Apps Script spec", "Automation", ["Apps Script", "Google Sheets", "Google Drive", "Gmail"], "Create a technical build plan with safe defaults.", `Create an Apps Script implementation spec for this GGW workflow: [WORKFLOW]. Source Sheet/Form: [SOURCE]. Desired output: [OUTPUT]. Return trigger type, required columns/config values, exact sequence, validation rules, duplicate protection, permission scopes to review, logging/status column, error handling, Gmail DRAFT-first behavior, testing plan with fictional data, and rollback/disable steps. Do not write code until the specification has no unresolved source or permission questions.`, ["apps script", "automation", "spec", "google"]),

  p("ai-privacy-check", "Decide what data is safe to give AI", "Research", ["Gemini"], "Minimize data before prompting.", `Review the information I plan to use for this GGW AI task: [DATA DESCRIPTION]. Task: [TASK]. Return REQUIRED FOR TASK, NOT NEEDED, SENSITIVE/NEEDS POLICY CHECK, and SAFE PLACEHOLDER/AGGREGATION options. Prefer removing names, contact details, payment data, HR/legal information, donor/member details, and identifiers unless they are truly required and approved. Do not decide GGW policy; identify where an owner/admin decision is required.`, ["privacy", "data minimization", "governance"]),
  p("ai-output-qa", "Final AI output quality check", "Research", ["Gemini"], "Use a consistent last-mile check before sharing AI-assisted work.", `Perform a final GGW AI-output QA check. OUTPUT: [PASTE]. AUTHORITATIVE SOURCE/REQUIREMENTS: [PASTE]. Check names, dates, times/time zones, URLs, amounts, percentages, eligibility, membership/event status, quotes, commitments, attachments/references, unsupported claims, privacy, audience/tone, and accessibility. Return PASS, FIX, and HUMAN DECISION sections. Do not silently correct facts; show each discrepancy.`, ["qa", "verification", "ai", "governance"]),
];

export const promptOutcomes = Array.from(new Set(prompts.map((item) => item.outcome)));
export const promptTools = Array.from(new Set(prompts.flatMap((item) => item.tools)));
