"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { Check, Copy, Search, Sparkles } from "lucide-react";

type Outcome = "Members" | "Events" | "Communications" | "Reporting" | "Content" | "Automation" | "Meetings";
type PromptItem = { id: string; title: string; tool: string; outcome: Outcome; summary: string; prompt: string; tags: string[] };

const prompts: PromptItem[] = [
  { id:"wa-segments", title:"Find useful member segments", tool:"WildApricot", outcome:"Members", summary:"Turn an approved member export into supported, non-sensitive segments.", tags:["members","segments","sheets"], prompt:"Review this GGW WildApricot member export for [GOAL]. Suggest useful segments using only fields present in the export. For each segment show the exact rule, count if available, why it matters, and recommended next action. Flag missing/inconsistent data. Do not infer sensitive attributes, intent, eligibility, or personal characteristics that are not explicitly present." },
  { id:"wa-welcome", title:"Draft a new-member welcome", tool:"WildApricot", outcome:"Members", summary:"Create a warm first-touch message from approved membership facts.", tags:["welcome","members","gmail"], prompt:"Draft a personalized GGW welcome email using only these approved WildApricot fields: first name [NAME], membership type [TYPE], join date [DATE], approved benefits [BENEFITS], and next step [NEXT STEP]. Keep it under 180 words and human. Return subject, body, CTA, and CHECK BEFORE SENDING. Do not invent benefits, discounts, events, contacts, or eligibility." },
  { id:"wa-renewal", title:"Prepare renewal outreach", tool:"WildApricot", outcome:"Members", summary:"Draft renewal messaging for a defined member segment.", tags:["renewal","members","email"], prompt:"Draft GGW renewal outreach for this approved segment: [SEGMENT]. Current status: [STATUS]. Approved benefits/facts: [FACTS]. Deadline/next step: [NEXT STEP]. Return subject, preview text, concise email, CTA, and optional reminder. Do not invent benefits, discounts, deadlines, eligibility, or member status. Add CHECK BEFORE SENDING." },
  { id:"wa-reengage", title:"Prepare lapsed-member re-engagement", tool:"WildApricot", outcome:"Members", summary:"Create re-engagement copy without inventing status or offers.", tags:["lapsed","reengagement","members"], prompt:"Create GGW re-engagement outreach for members matching this approved WildApricot rule: [RULE]. Approved reason to reconnect: [REASON]. Approved facts/offers: [FACTS]. Return subject, email, CTA, and one optional follow-up. Do not invent discounts, benefits, status, or eligibility. Mark missing information [CHECK]." },
  { id:"wa-event-copy", title:"Create event copy from the source record", tool:"WildApricot", outcome:"Events", summary:"Turn one approved event record into channel-ready copy.", tags:["events","promotion","copy"], prompt:"Using only these approved WildApricot event facts [PASTE FACTS], create: member email, LinkedIn post, short social caption, five talking points, and a fact-check list. Preserve event name, date, time, location, registration URL, deadline, pricing, and eligibility exactly. Mark missing items [CHECK] instead of inventing them." },
  { id:"wa-followup", title:"Build post-event follow-up", tool:"WildApricot", outcome:"Events", summary:"Prepare follow-up for attendees, no-shows, speakers, and internal owners.", tags:["followup","events","registrations"], prompt:"Using these approved WildApricot event details and registration fields, prepare GGW post-event follow-up for: attendees, no-shows, speakers/partners, and the internal team. Use only provided facts. Preserve links, names, dates, and commitments exactly. Add CHECK BEFORE SENDING to each external version." },
  { id:"wa-reg-analysis", title:"Analyze event registrations", tool:"WildApricot", outcome:"Reporting", summary:"Find patterns, follow-up groups, and data-quality issues.", tags:["registrations","analysis","sheets"], prompt:"Analyze this GGW WildApricot registration export for [GOAL]. Return registration count, useful non-sensitive groups, cancellations/no-shows if present, missing/inconsistent fields, follow-up needs, and five operational questions. Use only provided fields. Separate facts from recommendations and identify the field/pattern behind each recommendation." },
  { id:"wa-weekly", title:"Create a weekly WildApricot operations brief", tool:"WildApricot", outcome:"Reporting", summary:"Summarize membership and event changes without exposing unnecessary personal data.", tags:["weekly","operations","reporting"], prompt:"Create a concise GGW weekly operations brief from this approved WildApricot data for [DATE RANGE]. Return: what changed, member signals, event signals, exceptions/data-quality issues, actions with owner if provided, and questions needing a decision. Separate facts from recommendations. Do not expose unnecessary personal data." },

  { id:"gmail-draft", title:"Draft a clear GGW email", tool:"Gmail", outcome:"Communications", summary:"Turn approved facts and an intended action into a concise message.", tags:["email","draft","communication"], prompt:"Draft a concise GGW email. Audience: [AUDIENCE]. Purpose: [PURPOSE]. Desired action: [ACTION]. Approved facts: [FACTS]. Tone: confident, welcoming, inclusive, human. Return subject, preview text, body, CTA, and CHECK BEFORE SENDING. Do not invent dates, links, decisions, promises, or benefits." },
  { id:"gmail-thread", title:"Turn a long email thread into decisions and actions", tool:"Gmail", outcome:"Communications", summary:"Extract what matters from a long thread before replying.", tags:["email","summary","actions"], prompt:"Summarize this GGW email thread. Return: decision(s) already made, open questions, action items with owner/date only if stated, requested response, and a short reply draft. If an owner/date is not stated, write Not stated. Do not invent commitments. Finish with CHECK BEFORE SENDING." },
  { id:"gmail-tone", title:"Make an email shorter and more human", tool:"Gmail", outcome:"Communications", summary:"Improve tone without changing facts or commitments.", tags:["rewrite","tone","email"], prompt:"Rewrite this GGW email to be shorter, warmer, and more direct while preserving every factual statement, date, link, amount, commitment, and CTA exactly: [EMAIL]. Do not add new promises or information. Return the revised email plus a list of facts that must be checked before sending." },
  { id:"gmail-reminder", title:"Draft a respectful reminder", tool:"Gmail", outcome:"Communications", summary:"Create a useful follow-up without sounding automated or pushy.", tags:["reminder","followup","email"], prompt:"Draft a respectful GGW reminder. Audience: [AUDIENCE]. Original request: [REQUEST]. Approved deadline: [DEADLINE OR NONE]. Desired next step: [ACTION]. Keep it brief, human, and low-pressure. Do not invent urgency, penalties, deadlines, or commitments. Return subject, body, CTA, and CHECK BEFORE SENDING." },

  { id:"sheets-clean", title:"Plan a safe cleanup of a messy Sheet", tool:"Google Sheets", outcome:"Reporting", summary:"Standardize dates/labels and flag issues without changing the source first.", tags:["cleanup","data","duplicates"], prompt:"Review this Google Sheet structure/data for cleanup. Goal: [GOAL]. Propose a working-copy cleanup plan for dates, duplicate rows, blank required fields, inconsistent labels, and obvious formatting issues. Return the exact checks/formulas or steps to use, what not to change automatically, and a validation sample plan. Do not overwrite or infer missing values." },
  { id:"sheets-summary", title:"Summarize a Sheet for leadership", tool:"Google Sheets", outcome:"Reporting", summary:"Turn approved metrics into a concise operational narrative.", tags:["metrics","leadership","summary"], prompt:"Turn these approved GGW Sheet metrics into a concise leadership brief. Return executive headline, 3–5 key facts, what changed versus the comparison period if provided, risks/questions, and recommended next steps. Use only supplied data. Do not infer causation, ROI, or impact without explicit evidence. Mark unsupported claims [CHECK]." },
  { id:"sheets-formula", title:"Get help writing a Sheets formula", tool:"Google Sheets", outcome:"Reporting", summary:"Describe the desired result and get a formula plus a safe test plan.", tags:["formula","sheets","help"], prompt:"Write a Google Sheets formula for this task: [TASK]. Relevant columns/ranges: [RANGES]. Return the formula, plain-English explanation, one example result, common failure cases, and how to test it on a copy before applying broadly. If the structure is unclear, ask one focused question instead of guessing." },
  { id:"sheets-compare", title:"Compare two lists safely", tool:"Google Sheets", outcome:"Reporting", summary:"Find matches, missing records, and differences using explicit keys.", tags:["compare","lookup","records"], prompt:"Help compare these two GGW lists in Google Sheets. Primary match key: [KEY]. Goal: [GOAL]. Return a method/formulas for exact matches, records only in list A, records only in list B, and conflicting values. Explain duplicate-key risks and how to validate a sample before acting on the result." },
  { id:"sheets-questions", title:"Find the right questions in a dataset", tool:"Google Sheets", outcome:"Reporting", summary:"Turn a data dump into an investigation plan before drawing conclusions.", tags:["analysis","questions","data"], prompt:"Review the structure and approved summary of this GGW dataset: [FIELDS / SUMMARY]. Goal: [GOAL]. Return ten useful operational questions the data can actually answer, five it cannot answer safely, the fields needed for each question, and any data-quality checks to run first. Do not infer sensitive attributes or unsupported causation." },

  { id:"docs-brief", title:"Turn notes into a clean one-page brief", tool:"Google Docs", outcome:"Content", summary:"Organize rough notes into a decision-ready document.", tags:["brief","docs","summary"], prompt:"Turn these GGW notes into a one-page brief. Audience: [AUDIENCE]. Decision/outcome needed: [OUTCOME]. Return: purpose, current state, key facts, options/considerations, recommendation only if supported, open questions, and next actions. Use only supplied information and mark missing facts [CHECK]." },
  { id:"docs-sop", title:"Turn a process into a step-by-step SOP", tool:"Google Docs", outcome:"Content", summary:"Create a usable operating guide from an approved process.", tags:["sop","process","instructions"], prompt:"Turn this approved GGW process into a practical SOP: [PROCESS NOTES]. Return: purpose, when to use it, prerequisites, numbered steps, decision points, final verification, common failure points, and owner/escalation placeholders. Do not invent systems, permissions, policies, or SLAs that are not provided." },
  { id:"docs-review", title:"Review a document for gaps before sharing", tool:"Google Docs", outcome:"Content", summary:"Catch unsupported claims, missing decisions, and unclear next steps.", tags:["review","quality","docs"], prompt:"Review this GGW document for readiness to share. Check: factual support, dates/names/links, unsupported claims, ambiguous wording, missing decisions, missing owners/dates, privacy concerns, and CTA clarity. Return Issues to fix, Questions to resolve, and a revised section only where needed. Do not introduce new facts." },

  { id:"drive-find", title:"Plan a smarter Drive search", tool:"Google Drive", outcome:"Content", summary:"Turn a vague request into specific search terms and source checks.", tags:["drive","search","source"], prompt:"Help me find the correct GGW source file in Google Drive for [TASK]. Known details: [DETAILS]. Return likely search terms, useful filters, file-owner/date checks, and how to confirm I have the current approved source before using AI. Do not claim you can see Drive unless access is actually provided." },
  { id:"drive-govern", title:"Check a Drive file before sharing", tool:"Google Drive", outcome:"Content", summary:"Review access, ownership, sensitivity, and source status before distribution.", tags:["drive","sharing","permissions"], prompt:"Give me a final Google Drive sharing checklist for this GGW file: [FILE PURPOSE]. Audience: [AUDIENCE]. Sensitivity: [LEVEL]. Include owner/current-version check, link-access setting, group vs individual access, download/copy concerns, sensitive-data check, and what to verify after sharing. Do not suggest public access unless explicitly required and approved." },

  { id:"calendar-agenda", title:"Create a focused meeting agenda", tool:"Google Calendar", outcome:"Meetings", summary:"Turn a calendar meeting into an outcome-driven agenda.", tags:["calendar","agenda","meeting"], prompt:"Create a concise GGW meeting agenda. Meeting: [MEETING]. Purpose: [PURPOSE]. Attendees/roles: [ATTENDEES]. Desired decisions: [DECISIONS]. Time available: [MINUTES]. Return agenda with timeboxes, pre-read, decisions needed, and owner for follow-up only if supplied. Keep discussion that does not support the outcome out of the agenda." },
  { id:"calendar-invite", title:"Improve a calendar invite", tool:"Google Calendar", outcome:"Meetings", summary:"Make the purpose, preparation, and decision clear before people join.", tags:["invite","calendar","meeting"], prompt:"Rewrite this GGW calendar invitation so attendees know exactly why they are needed: [INVITE]. Return meeting purpose, expected outcome/decision, required preparation, agenda bullets, and what people can skip if not relevant. Preserve the existing date/time/location and do not invent decisions or requirements." },

  { id:"meet-actions", title:"Turn Meet notes into actions", tool:"Google Meet", outcome:"Meetings", summary:"Separate decisions, open questions, and owners after a meeting.", tags:["meet","actions","followup"], prompt:"Turn these GGW meeting notes/approved recap into: decisions, open questions, action items with owner and due date only if stated, risks/blockers, and a short follow-up email. If owner/date is not stated, write Not stated. Do not invent commitments. Finish with CHECK BEFORE SHARING." },
  { id:"meet-exec", title:"Create an executive recap from a meeting", tool:"Google Meet", outcome:"Meetings", summary:"Condense a long discussion into what leadership actually needs.", tags:["meet","executive","recap"], prompt:"Create a short executive recap from these GGW meeting notes. Return: why the meeting happened, decisions, key facts, unresolved issues, business impact only if explicitly supported, and next actions. Keep it under [LENGTH]. Do not invent owners, dates, risks, or conclusions." },

  { id:"slides-outline", title:"Build a presentation outline from approved content", tool:"Google Slides", outcome:"Content", summary:"Create a logical deck before formatting slides.", tags:["slides","deck","outline"], prompt:"Create a GGW presentation outline from these approved facts/notes: [CONTENT]. Audience: [AUDIENCE]. Desired outcome: [OUTCOME]. Return slide-by-slide purpose, headline, supporting facts, recommended visual, and speaker note. Use only supplied information; mark gaps [CHECK]. Avoid generic filler slides." },
  { id:"slides-board", title:"Turn metrics into a board deck story", tool:"Google Slides", outcome:"Reporting", summary:"Create a concise narrative without overstating results.", tags:["slides","board","metrics"], prompt:"Create a board-ready GGW slide story from these approved metrics and notes: [DATA]. Return 6–8 slides maximum: executive headline, key facts, trend/comparison if supplied, implications labeled as interpretation, risks/questions, and next steps. Cite the source/period on each metric slide. Do not infer causation or ROI without evidence." },

  { id:"notebook-sources", title:"Ask NotebookLM questions using approved sources", tool:"NotebookLM", outcome:"Content", summary:"Get answers grounded in selected GGW files with citations.", tags:["notebooklm","research","sources"], prompt:"Using only the sources loaded in this NotebookLM notebook, answer: [QUESTION]. Return the answer, source citations for each major claim, where sources disagree, and what the sources do not establish. Do not fill gaps with outside knowledge unless I explicitly ask for it." },
  { id:"notebook-brief", title:"Create a source-grounded briefing", tool:"NotebookLM", outcome:"Reporting", summary:"Synthesize multiple approved documents without losing traceability.", tags:["notebooklm","brief","citations"], prompt:"Create a GGW briefing from only the sources in this NotebookLM notebook. Audience: [AUDIENCE]. Goal: [GOAL]. Return key findings, evidence/citations, disagreements or outdated information, open questions, and recommended next research steps. Clearly separate source facts from recommendations." },

  { id:"gemini-task", title:"Turn a vague task into a strong Gemini request", tool:"Gemini", outcome:"Content", summary:"Use a simple structure when you are not sure how to prompt.", tags:["gemini","prompting","help"], prompt:"Help me complete this GGW task: [TASK]. Audience: [AUDIENCE]. Source I am allowed to use: [SOURCE]. Desired output: [FORMAT]. Constraints: [CONSTRAINTS]. First tell me if anything essential is missing. Then produce a concise first draft using only supplied information and finish with a verification checklist." },
  { id:"gemini-check", title:"Fact-check an AI draft against the source", tool:"Gemini", outcome:"Content", summary:"Use Gemini as a review assistant, not the final authority.", tags:["gemini","review","factcheck"], prompt:"Compare this draft [DRAFT] against this approved source [SOURCE]. Create a table with: draft claim, source support, status Supported / Unsupported / Needs clarification, and exact correction needed. Check names, dates, amounts, links, eligibility, commitments, and statistics. Do not use outside information." },

  { id:"canva-event", title:"Create a Canva event production brief", tool:"Canva", outcome:"Events", summary:"Prepare approved copy and layout direction before opening the template.", tags:["canva","events","visual"], prompt:"Create a Canva production brief for a GGW event using only these approved WildApricot facts: [FACTS]. Return headline, supporting copy, CTA, visual hierarchy, image direction, and alt text. Preserve dates, times, prices, eligibility, location, and URLs exactly. Mark missing information [CHECK]." },
  { id:"canva-social", title:"Shorten copy for a resized Canva design", tool:"Canva", outcome:"Content", summary:"Keep essential facts when adapting a design for another format.", tags:["canva","resize","social"], prompt:"Shorten this approved GGW copy for [CHANNEL / FORMAT] while preserving the event name, date, time, CTA, registration URL, eligibility, and required wording exactly: [COPY]. Return one concise version plus a CHECK list for the resized design. Do not introduce new claims or hashtags unless provided." },
  { id:"canva-board", title:"Create a board-visual brief", tool:"Canva", outcome:"Reporting", summary:"Choose a clear visual structure for approved metrics.", tags:["canva","board","metrics"], prompt:"Using only these approved GGW metrics and definitions [METRICS], create a Canva-ready leadership visual brief. Return recommended headline, chart/table format, 3 supporting facts, a short interpretation labeled Recommendation, and a source-note format. Do not infer causation, ROI, or impact not explicitly supported." },
  { id:"canva-spotlight", title:"Create approved spotlight copy", tool:"Canva", outcome:"Content", summary:"Prepare safe copy for a member, speaker, volunteer, or partner visual.", tags:["canva","spotlight","people"], prompt:"Create concise GGW spotlight copy using only this approved information: [BIO / ROLE / QUOTE / EVENT FACTS]. Return headline, 60-word spotlight, short social caption, and alt text. Do not add achievements, personal details, quotes, affiliations, or claims that are not supplied. Mark missing items [CHECK]." },
  { id:"canva-template", title:"Plan a reusable Canva template", tool:"Canva", outcome:"Automation", summary:"Define fixed brand elements and variable fields for repeatable assets.", tags:["canva","template","repeatable"], prompt:"Design the content structure for a reusable GGW Canva template for [ASSET TYPE]. Approved source systems: [SOURCES]. Return fixed brand elements, variable fields, placeholder labels, source for each variable field, final review checklist, and short user instruction. Do not suggest fields that are not available in the named sources." },

  { id:"zapier-design", title:"Design a simple WildApricot → Google Zap", tool:"Zapier", outcome:"Automation", summary:"Plan trigger, field mapping, review gate, duplicate protection, and test steps.", tags:["zapier","wildapricot","google"], prompt:"Design a safe Zapier workflow for GGW. Business outcome: [OUTCOME]. WildApricot trigger: [TRIGGER]. Google destination/action: [ACTION]. Return trigger, minimum required fields, field mapping, optional AI step, human review gate, duplicate protection, failure alert, test plan, and how to turn it off. Keep WildApricot as the system of record." },
  { id:"zapier-troubleshoot", title:"Troubleshoot a Zap before turning it on", tool:"Zapier", outcome:"Automation", summary:"Check mapping, duplicates, permissions, and failure handling.", tags:["zapier","test","troubleshoot"], prompt:"Review this GGW Zap design before activation: [WORKFLOW]. Return a test checklist covering trigger sample, account/permission check, field mapping, missing fields, duplicate behavior, updates/cancellations, external-message draft mode, failure alerts, and rollback/disable steps. Flag any step that can change a WildApricot record or send externally without review." },

  { id:"make-design", title:"Design a multi-step Make scenario", tool:"Make", outcome:"Automation", summary:"Plan a branching workflow when a simple Zap is not enough.", tags:["make","scenario","automation"], prompt:"Design a safe Make scenario for GGW. Outcome: [OUTCOME]. Source/trigger: [SOURCE]. Required branches: [BRANCHES]. Destinations: [DESTINATIONS]. Return modules in order, minimum fields, filters/routes, AI transformation steps, human approval points, error route, duplicate/idempotency approach, test cases, and shutdown procedure. Do not allow AI to make unreviewed membership/financial record changes." },

  { id:"forms-summary", title:"Turn a Google Form response set into an action summary", tool:"Google Forms", outcome:"Reporting", summary:"Use the response Sheet as the working layer and summarize what needs attention.", tags:["forms","responses","sheets"], prompt:"Using this approved Google Forms response summary/Sheet data for [FORM PURPOSE], return response count, missing required information, useful non-sensitive groups, repeated themes, exceptions needing follow-up, and actions with owner only if provided. Do not infer sensitive attributes or intent. Separate facts from recommendations." },
];

const outcomes: Array<"All" | Outcome> = ["All","Members","Events","Communications","Reporting","Content","Automation","Meetings"];

function PromptCard({ item }: { item: PromptItem }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try { await navigator.clipboard.writeText(item.prompt); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); }
  };
  return <article className="ggw-pw-card">
    <div className="ggw-pw-card-top"><div><span>{item.tool}</span><em>{item.outcome}</em></div><button onClick={copy}>{copied ? <Check size={14}/> : <Copy size={14}/>} {copied ? "Copied" : "Copy"}</button></div>
    <h3>{item.title}</h3><p>{item.summary}</p><div className="ggw-pw-prompt">{item.prompt}</div>
    <div className="ggw-pw-tags">{item.tags.map(tag => <span key={tag}>#{tag}</span>)}</div>
  </article>;
}

function PromptToolbox() {
  const [query, setQuery] = useState("");
  const [tool, setTool] = useState("All");
  const [outcome, setOutcome] = useState<"All" | Outcome>("All");
  const tools = useMemo(() => ["All", ...Array.from(new Set(prompts.map(item => item.tool))).sort()], []);
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return prompts.filter(item => {
      const toolMatch = tool === "All" || item.tool === tool;
      const outcomeMatch = outcome === "All" || item.outcome === outcome;
      const haystack = `${item.title} ${item.summary} ${item.tool} ${item.outcome} ${item.tags.join(" ")}`.toLowerCase();
      return toolMatch && outcomeMatch && (!q || haystack.includes(q));
    });
  }, [query, tool, outcome]);

  return <main className="ggw-prompt-workbench" aria-labelledby="ggw-prompt-title">
    <header className="ggw-pw-hero"><span><Sparkles size={15}/> GGW PROMPT TOOLBOX</span><h1 id="ggw-prompt-title">Find the prompt for the job.</h1><p>Choose the tool you are using, narrow by outcome, or describe what you need. Replace the brackets with approved information and always run the final check before sending, publishing, or changing a record.</p></header>
    <section className="ggw-pw-controls" aria-label="Prompt filters">
      <label className="ggw-pw-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try: renewal email, event graphic, board report, Sheet cleanup…" aria-label="Search prompts"/>{query && <button onClick={()=>setQuery("")} aria-label="Clear prompt search">×</button>}</label>
      <div className="ggw-pw-filter-block"><strong>Solution</strong><div className="ggw-pw-filters">{tools.map(value => <button key={value} className={tool===value?"active":""} onClick={()=>setTool(value)} aria-pressed={tool===value}>{value}</button>)}</div></div>
      <div className="ggw-pw-filter-block"><strong>Work outcome</strong><div className="ggw-pw-filters">{outcomes.map(value => <button key={value} className={outcome===value?"active":""} onClick={()=>setOutcome(value)} aria-pressed={outcome===value}>{value}</button>)}</div></div>
      <div className="ggw-pw-result-count"><strong>{filtered.length}</strong><span>{filtered.length===1?"prompt":"prompts"} ready to use</span>{(query || tool!=="All" || outcome!=="All") && <button onClick={()=>{setQuery("");setTool("All");setOutcome("All");}}>Reset filters</button>}</div>
    </section>
    {filtered.length ? <section className="ggw-pw-grid">{filtered.map(item => <PromptCard key={item.id} item={item}/>)}</section> : <section className="ggw-pw-empty"><strong>No prompt matches that combination.</strong><span>Reset the filters or search by the work you are trying to complete.</span></section>}
    <footer className="ggw-pw-foot"><strong>GGW rule of thumb</strong><span>AI prepares. A person verifies names, dates, links, amounts, eligibility, recipients, commitments, permissions, and anything that changes the system of record.</span></footer>
  </main>;
}

export default function PromptWorkbench() {
  const [show, setShow] = useState(false);
  const [ready, setReady] = useState(false);
  useEffect(() => {
    setReady(true);
    const sync = () => setShow(document.body.dataset.ggwWorkbenchView === "prompts" || window.location.pathname.includes("/prompts"));
    sync();
    const observer = new MutationObserver(sync);
    observer.observe(document.body,{attributes:true,attributeFilter:["data-ggw-workbench-view"],childList:true,subtree:true});
    window.addEventListener("popstate",sync);
    return ()=>{observer.disconnect();window.removeEventListener("popstate",sync);};
  },[]);
  useEffect(()=>{ if(show) document.body.dataset.ggwPromptToolbox="true"; else delete document.body.dataset.ggwPromptToolbox; return()=>{delete document.body.dataset.ggwPromptToolbox;};},[show]);
  if(!ready || !show) return null;
  return createPortal(<PromptToolbox/>,document.body);
}
