"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Download, FileSpreadsheet, ShieldCheck, Sparkles, Upload } from "lucide-react";
import GoogleDriveCsvPicker from "@/app/components/google-drive-csv-picker";
import "./data-cleanup.css";

type DataKind="members"|"events"|"sponsors"|"other";type Row=Record<string,string>;type Finding={label:string;count:number;detail:string};
const sampleCsv=`First Name,Last Name,Email,Company,Event Date\nJANE,DOE,jane@example.com,global gaming women,9/2/26\nJane,Doe,jane@example.com,Global Gaming Women,2026-09-02\nsam,lee,sam @example.com,Example Sponsor,September 3 2026\n,Avery,avery@example.com,Example Sponsor,09-03-2026`;
function parseCsv(input:string):{headers:string[];rows:Row[];error?:string}{const text=input.replace(/^\uFEFF/,"").trim();if(!text)return{headers:[],rows:[]};const records:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))records.push(row);row=[];cell=""}else cell+=c}if(quoted)return{headers:[],rows:[],error:"A quoted field appears incomplete."};row.push(cell);if(row.some(v=>v.trim()))records.push(row);if(records.length<2)return{headers:[],rows:[],error:"Add a header row and at least one data row."};const seen=new Map<string,number>();const headers=records[0].map((v,i)=>{const base=v.trim()||`Column ${i+1}`;const c=seen.get(base.toLowerCase())||0;seen.set(base.toLowerCase(),c+1);return c?`${base} (${c+1})`:base});return{headers,rows:records.slice(1).map(values=>{const out:Row={};headers.forEach((h,i)=>out[h]=(values[i]||"").trim());return out})}}
const titleCase=(v:string)=>v.trim().toLowerCase().replace(/\b([a-z])/g,m=>m.toUpperCase());const cleanEmail=(v:string)=>v.trim().toLowerCase().replace(/\s+/g,"");const emailCol=(h:string)=>/email/i.test(h);const nameCol=(h:string)=>/(first name|last name|full name|(^|\s)name($|\s))/i.test(h);const orgCol=(h:string)=>/company|organization|organisation|sponsor/i.test(h);const dateCol=(h:string)=>/date/i.test(h);function normDate(v:string){if(!v.trim())return v;const d=new Date(v);if(Number.isNaN(d.getTime()))return v;return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}const validEmail=(v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);const esc=(v:string)=>/[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v;
export default function DataCleanupPage(){const[kind,setKind]=useState<DataKind>("members");const[input,setInput]=useState("");const[fileName,setFileName]=useState("");const[hasRun,setHasRun]=useState(false);const[loadError,setLoadError]=useState("");const parsed=useMemo(()=>parseCsv(input),[input]);const cleanedRows=useMemo(()=>parsed.rows.map(source=>{const c:Row={};parsed.headers.forEach(h=>{const v=source[h]??"";if(emailCol(h))c[h]=cleanEmail(v);else if(nameCol(h)||orgCol(h))c[h]=titleCase(v);else if(dateCol(h))c[h]=normDate(v);else c[h]=v.trim()});return c}),[parsed]);const diagnostics=useMemo(()=>{const blanks=parsed.rows.reduce((t,r)=>t+parsed.headers.filter(h=>!r[h]?.trim()).length,0);const emails=parsed.headers.filter(emailCol);const bad=cleanedRows.reduce((t,r)=>t+emails.filter(h=>r[h]&&!validEmail(r[h])).length,0);const seen=new Set<string>();let dup=0;const primary=emails[0];if(primary)cleanedRows.forEach(r=>{const k=r[primary]?.toLowerCase();if(!k)return;if(seen.has(k))dup++;else seen.add(k)});let changes=0;parsed.rows.forEach((r,i)=>parsed.headers.forEach(h=>{if((r[h]||"")!==(cleanedRows[i]?.[h]||""))changes++}));return[{label:"Formatting fixes",count:changes,detail:"Whitespace, capitalization, email spacing/case, and recognizable dates."},{label:"Duplicate records",count:dup,detail:primary?"Potential duplicates based on the first email column.":"No email column found."},{label:"Invalid emails",count:bad,detail:"Emails that still need human review."},{label:"Blank fields",count:blanks,detail:"Missing values are flagged, never invented."}] as Finding[]},[parsed,cleanedRows]);const issueCount=diagnostics.reduce((s,f)=>s+f.count,0);
 function loadText(text:string,name:string){setInput(text);setFileName(name);setHasRun(true);setLoadError("")}
 async function upload(file?:File){if(!file)return;if(file.size>5_000_000){setLoadError("CSV is too large. Use a file under 5 MB.");return}try{loadText(await file.text(),file.name)}catch{setLoadError("Could not read that CSV.")}}
 function downloadCsv(){if(!parsed.headers.length||!cleanedRows.length)return;const body=[parsed.headers.map(esc).join(","),...cleanedRows.map(r=>parsed.headers.map(h=>esc(r[h]||"")).join(","))].join("\n");const url=URL.createObjectURL(new Blob([body],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`ggw-cleaned-${kind}.csv`;a.click();URL.revokeObjectURL(url)}
 return <main className="cleanup-page"><section className="cleanup-hero"><div className="cleanup-eyebrow"><Sparkles size={16}/> GGW Data Cleanup Workbench</div><h1>Turn a messy spreadsheet into something you can trust.</h1><p>Upload a CSV, choose a Google Sheet, or paste data. Review safe cleanup changes before exporting.</p><div className="cleanup-trust"><ShieldCheck size={18}/><span>Your original source is never overwritten.</span></div></section>
 <section className="cleanup-card cleanup-start"><div className="cleanup-step"><span>1</span><div><strong>What are you cleaning?</strong><small>Choose the closest data type.</small></div></div><div className="kind-grid">{([['members','Membership roster','Names, emails, companies, membership data'],['events','Event registrations','Attendees, dates, registration fields'],['sponsors','Sponsors / donors','Organizations, contacts, status fields'],['other','Other spreadsheet','Any CSV-style operational list']] as Array<[DataKind,string,string]>).map(([id,title,description])=><button key={id} className={kind===id?"kind-card active":"kind-card"} onClick={()=>setKind(id)}><FileSpreadsheet size={21}/><strong>{title}</strong><span>{description}</span></button>)}</div></section>
 <section className="cleanup-card"><div className="cleanup-step"><span>2</span><div><strong>Import your spreadsheet</strong><small>CSV upload is fastest. Google Sheets can be selected directly from Drive.</small></div></div><div className="cleanup-actions"><label className="primary-action" style={{cursor:"pointer"}}><Upload size={17}/> Upload CSV<input type="file" accept=".csv,text/csv" style={{display:"none"}} onChange={e=>upload(e.target.files?.[0])}/></label><GoogleDriveCsvPicker onCsv={loadText}/><button className="secondary-action" onClick={()=>loadText(sampleCsv,"messy-sample.csv")}>Try a messy sample</button></div>{fileName&&<p className="preview-note"><strong>Loaded:</strong> {fileName}</p>}{loadError&&<div className="error-box"><AlertTriangle size={18}/><span>{loadError}</span></div>}<details><summary style={{cursor:"pointer",fontWeight:700}}>Or paste CSV manually</summary><textarea aria-label="CSV data" value={input} onChange={e=>{setInput(e.target.value);setHasRun(false);setFileName("")}} placeholder="First Name,Last Name,Email,Company..."/><button className="primary-action" onClick={()=>setHasRun(true)} disabled={!input.trim()}>Find problems</button></details>{hasRun&&parsed.error&&<div className="error-box"><AlertTriangle size={18}/><div><strong>We couldn’t read this data yet.</strong><span>{parsed.error}</span></div></div>}</section>
 {hasRun&&!parsed.error&&parsed.rows.length>0&&<><section className="cleanup-results"><div className="result-banner"><CheckCircle2 size={26}/><div><strong>{parsed.rows.length.toLocaleString()} records checked</strong><span>{issueCount.toLocaleString()} cleanup/review items found.</span></div></div><div className="finding-grid">{diagnostics.map(f=><article key={f.label} className="finding-card"><b>{f.count}</b><strong>{f.label}</strong><span>{f.detail}</span></article>)}</div></section><section className="cleanup-card"><div className="cleanup-step"><span>3</span><div><strong>Preview before exporting</strong><small>Highlighted formatting changes are safe; invalid emails remain visible for review.</small></div></div><div className="table-wrap"><table><thead><tr>{parsed.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{cleanedRows.slice(0,12).map((r,i)=><tr key={i}>{parsed.headers.map(h=>{const o=parsed.rows[i]?.[h]||"",c=r[h]||"",bad=emailCol(h)&&c&&!validEmail(c);return<td key={h} className={bad?"needs-review":o!==c?"changed":""}>{c||<em>Blank</em>}</td>})}</tr>)}</tbody></table></div></section><section className="cleanup-card cleanup-export"><div className="cleanup-step"><span>4</span><div><strong>Export a cleaned copy</strong><small>Review duplicates, blanks, and invalid emails before replacing a source list.</small></div></div><button className="primary-action" onClick={downloadCsv}><Download size={17}/> Download cleaned CSV</button></section></>}
 </main>}
